% Top spam trigrams
spam_trigram("_", "_", "_").
spam_trigram("nbsp", "nbsp", "nbsp").
spam_trigram("computron", "me", "com").
spam_trigram("www", "computron", "me").
spam_trigram("forward", "looking", "statements").
spam_trigram("http", "69", "63").
spam_trigram("69", "63", "161").
spam_trigram("_", "nd", "_").
spam_trigram("a", "href", "http").
spam_trigram("the", "company", "s").
spam_trigram("if", "you", "have").
spam_trigram("color", "3", "d").
spam_trigram("this", "message", "is").
spam_trigram("63", "161", "44").
spam_trigram("src", "http", "69").
spam_trigram("ali", "duty", "free").
spam_trigram("reply", "to", "this").
spam_trigram("within", "this", "email").
spam_trigram("the", "publisher", "of").
spam_trigram("me", "com", "for").
spam_trigram("href", "http", "www").
spam_trigram("publisher", "of", "this").
spam_trigram("to", "be", "removed").
spam_trigram("of", "the", "securities").
spam_trigram("border", "0", "src").
spam_trigram("0", "src", "http").
spam_trigram("http", "www", "moopid").
spam_trigram("www", "moopid", "com").
spam_trigram("moopid", "com", "hotlist").
spam_trigram("in", "compliance", "with").
spam_trigram("td", "tr", "tr").
spam_trigram("td", "td", "width").
spam_trigram("risks", "and", "uncertainties").
spam_trigram("of", "this", "newsletter").
spam_trigram("copy", "and", "paste").
spam_trigram("pt", "font", "family").
spam_trigram("the", "securities", "act").
spam_trigram("securities", "act", "of").
spam_trigram("tr", "tr", "td").
spam_trigram("style", "line", "height").
spam_trigram("line", "height", "15").
spam_trigram("height", "15", "pt").
spam_trigram("15", "pt", "font").
spam_trigram("font", "family", "knle").
spam_trigram("family", "knle", "font").
spam_trigram("knle", "font", "size").
spam_trigram("font", "size", "9").
spam_trigram("size", "9", "pt").
spam_trigram("into", "your", "browser").
spam_trigram("src", "http", "www").
spam_trigram("iit", "demokritos", "gr").
spam_trigram("within", "this", "report").
spam_trigram("of", "this", "report").
spam_trigram("in", "the", "subject").
spam_trigram("compliance", "with", "the").
spam_trigram("you", "don", "t").
spam_trigram("within", "the", "meaning").
spam_trigram("the", "meaning", "of").
spam_trigram("act", "of", "1933").
spam_trigram("are", "based", "on").
spam_trigram("jebel", "ali", "duty").
spam_trigram("would", "like", "to").
spam_trigram("click", "here", "to").
spam_trigram("may", "not", "be").
spam_trigram("statements", "within", "the").
spam_trigram("size", "3", "d").
spam_trigram("href", "http", "69").
spam_trigram("this", "is", "a").
spam_trigram("to", "unsubscribe", "from").
spam_trigram("a", "td", "td").
spam_trigram("you", "have", "any").
spam_trigram("sent", "to", "you").
spam_trigram("face", "3", "darial").
spam_trigram("a", "number", "of").
spam_trigram("to", "you", "in").
spam_trigram("3", "d", "2").
spam_trigram("161", "44", "0310041").
spam_trigram("44", "0310041", "_").
spam_trigram("0310041", "_", "nd").
spam_trigram("nd", "_", "cf").
spam_trigram("act", "of", "1934").
spam_trigram("conflict", "of", "interest").
spam_trigram("if", "you", "wish").
spam_trigram("and", "paste", "the").
spam_trigram("is", "not", "a").
spam_trigram("and", "lots", "more").
spam_trigram("as", "long", "as").
spam_trigram("follow", "this", "link").
spam_trigram("63", "161", "45").
spam_trigram("subject", "to", "change").
spam_trigram("like", "to", "be").
spam_trigram("161", "45", "0424040").
spam_trigram("45", "0424040", "_").
spam_trigram("0424040", "_", "nd").
spam_trigram("nd", "_", "ftar").
spam_trigram("in", "error", "or").
spam_trigram("for", "any", "other").
spam_trigram("click", "the", "link").
spam_trigram("an", "inherent", "conflict").
spam_trigram("inherent", "conflict", "of").
spam_trigram("of", "the", "company").
spam_trigram("u", "s", "dollars").
spam_trigram("to", "receive", "our").
spam_trigram("to", "this", "mail").
spam_trigram("not", "be", "considered").
spam_trigram("or", "for", "any").
spam_trigram("windows", "xp", "professional").
spam_trigram("and", "may", "be").
spam_trigram("differ", "materially", "from").
spam_trigram("the", "use", "of").
spam_trigram("of", "these", "companies").
spam_trigram("you", "wish", "to").
spam_trigram("receive", "our", "special").
spam_trigram("plain", "text", "format").
spam_trigram("message", "is", "being").
spam_trigram("is", "being", "sent").
spam_trigram("being", "sent", "to").
spam_trigram("if", "you", "are").
spam_trigram("com", "hotlist", "images").
spam_trigram("materially", "from", "those").
spam_trigram("of", "the", "material").
spam_trigram("the", "material", "within").
spam_trigram("material", "within", "this").
spam_trigram("oil", "and", "gas").
spam_trigram("for", "further", "details").
spam_trigram("for", "export", "only").
spam_trigram("the", "subject", "line").
spam_trigram("with", "the", "federal").
spam_trigram("all", "logos", "and").
spam_trigram("logos", "and", "trademarks").
spam_trigram("and", "trademarks", "are").
spam_trigram("trademarks", "are", "the").
spam_trigram("are", "the", "property").
spam_trigram("the", "property", "of").
spam_trigram("property", "of", "their").
spam_trigram("of", "their", "respective").
spam_trigram("thank", "you", "for").
spam_trigram("looking", "statements", "within").
spam_trigram("your", "one", "stop").
spam_trigram("more", "if", "you").
spam_trigram("tel", "971", "4").
spam_trigram("971", "4", "8834464").
spam_trigram("4", "8834464", "all").
spam_trigram("8834464", "all", "prices").
spam_trigram("all", "prices", "in").
spam_trigram("prices", "in", "u").
spam_trigram("in", "u", "s").
spam_trigram("s", "dollars", "ex").
spam_trigram("dollars", "ex", "works").
spam_trigram("fax", "971", "4").
spam_trigram("971", "4", "8834454").
spam_trigram("duty", "free", "zone").
spam_trigram("me", "com", "prices").
spam_trigram("com", "prices", "and").
spam_trigram("prices", "and", "availability").
spam_trigram("and", "availability", "subject").
spam_trigram("availability", "subject", "to").
spam_trigram("usa", "canada", "u").
spam_trigram("canada", "u", "a").
spam_trigram("u", "a", "e").
spam_trigram("our", "special", "offers").
spam_trigram("special", "offers", "in").
spam_trigram("offers", "in", "plain").
spam_trigram("in", "plain", "text").
spam_trigram("text", "format", "reply").
spam_trigram("format", "reply", "to").
spam_trigram("this", "mail", "with").
spam_trigram("mail", "with", "the").
spam_trigram("with", "the", "request").
spam_trigram("this", "email", "can").
spam_trigram("email", "can", "not").
spam_trigram("can", "not", "be").
spam_trigram("be", "considered", "spam").
spam_trigram("considered", "spam", "as").
spam_trigram("spam", "as", "long").
spam_trigram("long", "as", "we").
spam_trigram("as", "we", "include").
spam_trigram("we", "include", "contact").
spam_trigram("include", "contact", "information").
spam_trigram("contact", "information", "remove").
spam_trigram("information", "remove", "instructions").
spam_trigram("remove", "instructions", "this").
spam_trigram("instructions", "this", "message").
spam_trigram("message", "is", "intended").
spam_trigram("is", "intended", "for").
spam_trigram("intended", "for", "dealer").
spam_trigram("for", "dealer", "and").
spam_trigram("dealer", "and", "resellers").
spam_trigram("and", "resellers", "only").
spam_trigram("resellers", "only", "if").
spam_trigram("only", "if", "you").
spam_trigram("you", "have", "somehow").
spam_trigram("have", "somehow", "gotten").
spam_trigram("somehow", "gotten", "on").
spam_trigram("gotten", "on", "this").
spam_trigram("on", "this", "list").
spam_trigram("this", "list", "in").
spam_trigram("list", "in", "error").
spam_trigram("error", "or", "for").
spam_trigram("any", "other", "reason").
spam_trigram("other", "reason", "would").
spam_trigram("reason", "would", "like").
spam_trigram("be", "removed", "please").
spam_trigram("removed", "please", "reply").
spam_trigram("please", "reply", "with").
spam_trigram("reply", "with", "remove").
spam_trigram("with", "remove", "in").
spam_trigram("remove", "in", "the").
spam_trigram("subject", "line", "of").
spam_trigram("line", "of", "your").
spam_trigram("of", "your", "message").
spam_trigram("your", "message", "this").
spam_trigram("message", "this", "message").
spam_trigram("you", "in", "compliance").
spam_trigram("the", "federal", "legislation").
spam_trigram("federal", "legislation", "for").
spam_trigram("legislation", "for", "commercial").
spam_trigram("for", "commercial", "e").
spam_trigram("commercial", "e", "mail").
spam_trigram("e", "mail", "h").
spam_trigram("mail", "h", "r").
spam_trigram("h", "r", "4176").
spam_trigram("r", "4176", "section").
spam_trigram("4176", "section", "101").
spam_trigram("section", "101", "paragraph").
spam_trigram("101", "paragraph", "e").
spam_trigram("paragraph", "e", "1").
spam_trigram("e", "1", "a").
spam_trigram("1", "a", "and").
spam_trigram("a", "and", "bill").
spam_trigram("and", "bill", "s").
spam_trigram("bill", "s", "1618").
spam_trigram("s", "1618", "title").
spam_trigram("1618", "title", "iii").
spam_trigram("title", "iii", "passed").
spam_trigram("iii", "passed", "by").
spam_trigram("passed", "by", "the").
spam_trigram("by", "the", "105").
spam_trigram("the", "105", "th").
spam_trigram("105", "th", "u").
spam_trigram("th", "u", "s").
spam_trigram("u", "s", "congress").
spam_trigram("s", "congress", "all").
spam_trigram("congress", "all", "logos").
spam_trigram("products", "may", "not").
spam_trigram("not", "be", "exactly").
spam_trigram("be", "exactly", "as").
spam_trigram("exactly", "as", "shown").
spam_trigram("as", "shown", "above").
spam_trigram("shown", "above", "to").
spam_trigram("above", "to", "unsubscribe").
spam_trigram("unsubscribe", "from", "computron").
spam_trigram("just", "follow", "this").
spam_trigram("this", "link", "click").
spam_trigram("link", "click", "the").
spam_trigram("the", "link", "or").
spam_trigram("link", "or", "copy").
spam_trigram("or", "copy", "and").
spam_trigram("paste", "the", "address").
spam_trigram("the", "address", "into").
spam_trigram("address", "into", "your").
spam_trigram("161", "44", "1226030").
spam_trigram("44", "1226030", "_").
spam_trigram("1226030", "_", "nd").
spam_trigram("nd", "_", "cs").
spam_trigram("_", "cs", "2").
spam_trigram("the", "securities", "exchange").
spam_trigram("securities", "exchange", "act").
spam_trigram("exchange", "act", "of").
spam_trigram("number", "of", "risks").
spam_trigram("should", "not", "be").
spam_trigram("com", "for", "latest").
spam_trigram("for", "latest", "clearance").
spam_trigram("latest", "clearance", "sale").
spam_trigram("clearance", "sale", "listing").
spam_trigram("sale", "listing", "contact").
spam_trigram("listing", "contact", "our").
spam_trigram("contact", "our", "sales").
spam_trigram("our", "sales", "department").
spam_trigram("please", "send", "your").
spam_trigram("me", "com", "compaq").
spam_trigram("com", "compaq", "hewlett").
spam_trigram("compaq", "hewlett", "packard").
spam_trigram("hewlett", "packard", "3").
spam_trigram("packard", "3", "com").
spam_trigram("3", "com", "dell").
spam_trigram("com", "dell", "intel").
spam_trigram("dell", "intel", "iomega").
spam_trigram("intel", "iomega", "epson").
spam_trigram("iomega", "epson", "aopen").
spam_trigram("epson", "aopen", "creative").
spam_trigram("aopen", "creative", "toshiba").
spam_trigram("creative", "toshiba", "apc").
spam_trigram("toshiba", "apc", "cisco").
spam_trigram("apc", "cisco", "us").
spam_trigram("cisco", "us", "robotics").
spam_trigram("us", "robotics", "microsoft").
spam_trigram("robotics", "microsoft", "canon").
spam_trigram("microsoft", "canon", "intellinet").
spam_trigram("canon", "intellinet", "targus").
spam_trigram("intellinet", "targus", "viewsonic").
spam_trigram("targus", "viewsonic", "ibm").
spam_trigram("viewsonic", "ibm", "sony").
spam_trigram("ibm", "sony", "and").
spam_trigram("sony", "and", "lots").
spam_trigram("have", "any", "complaints").
spam_trigram("any", "complaints", "suggestions").
spam_trigram("complaints", "suggestions", "contact").
spam_trigram("suggestions", "contact", "customerservice").
spam_trigram("contact", "customerservice", "computron").
spam_trigram("customerservice", "computron", "me").
spam_trigram("ex", "works", "fax").
spam_trigram("works", "fax", "971").
spam_trigram("4", "8834454", "jebel").
spam_trigram("8834454", "jebel", "ali").
spam_trigram("free", "zone", "www").
spam_trigram("to", "change", "usa").
spam_trigram("change", "usa", "canada").
spam_trigram("a", "e", "without").
spam_trigram("e", "without", "notice").
spam_trigram("adobe", "photoshop", "7").
spam_trigram("statements", "are", "based").
spam_trigram("be", "construed", "as").
spam_trigram("one", "of", "the").
spam_trigram("further", "details", "please").
spam_trigram("details", "please", "send").
spam_trigram("send", "your", "enquiries").
spam_trigram("your", "enquiries", "to").
spam_trigram("contact", "via", "www").
spam_trigram("via", "www", "computron").
spam_trigram("lots", "more", "if").
spam_trigram("me", "com", "tel").
spam_trigram("com", "tel", "971").
spam_trigram("zone", "www", "computron").
spam_trigram("without", "notice", "to").
spam_trigram("notice", "to", "receive").
spam_trigram("the", "request", "for").
spam_trigram("request", "for", "export").
spam_trigram("export", "only", "this").
spam_trigram("only", "this", "email").
spam_trigram("to", "differ", "materially").
spam_trigram("not", "investment", "advice").
spam_trigram("any", "kind", "of").
spam_trigram("be", "aware", "of").
spam_trigram("do", "not", "reply").
spam_trigram("meaning", "of", "section").
spam_trigram("of", "section", "27").
spam_trigram("of", "1933", "and").
spam_trigram("and", "section", "21").
spam_trigram("from", "a", "registered").
spam_trigram("a", "third", "party").
spam_trigram("you", "have", "been").
spam_trigram("duty", "free", "zonedubai").
spam_trigram("free", "zonedubai", "uae").
spam_trigram("zonedubai", "uae", "www").
spam_trigram("uae", "www", "computron").
spam_trigram("enquiries", "to", "dealers").
spam_trigram("to", "dealers", "emirates").
spam_trigram("dealers", "emirates", "net").
spam_trigram("emirates", "net", "aeor").
spam_trigram("net", "aeor", "contact").
spam_trigram("aeor", "contact", "via").
spam_trigram("visit", "http", "www").
spam_trigram("section", "27", "a").
spam_trigram("27", "a", "of").
spam_trigram("a", "of", "the").
spam_trigram("at", "the", "time").
spam_trigram("statements", "in", "this").
spam_trigram("information", "provided", "within").
spam_trigram("provided", "within", "this").
spam_trigram("pertaining", "to", "investing").
spam_trigram("securities", "must", "be").
spam_trigram("must", "be", "understood").
spam_trigram("be", "understood", "as").
spam_trigram("understood", "as", "information").
spam_trigram("as", "information", "provided").
spam_trigram("information", "provided", "and").
spam_trigram("provided", "and", "not").
spam_trigram("and", "not", "investment").
spam_trigram("to", "seek", "advice").
spam_trigram("seek", "advice", "from").
spam_trigram("advice", "from", "a").
spam_trigram("securities", "representative", "before").
spam_trigram("representative", "before", "deciding").
spam_trigram("before", "deciding", "to").
spam_trigram("deciding", "to", "trade").
spam_trigram("to", "trade", "in").
spam_trigram("featured", "within", "this").
spam_trigram("none", "of", "the").
spam_trigram("construed", "as", "any").
spam_trigram("as", "any", "kind").
spam_trigram("kind", "of", "investment").
spam_trigram("of", "investment", "advice").
spam_trigram("http", "www", "computron").
spam_trigram("com", "for", "deals").
spam_trigram("rnd", "_", "alt").
spam_trigram("china", "itoy", "com").
spam_trigram("with", "respect", "to").
spam_trigram("statements", "are", "made").
spam_trigram("may", "be", "identified").
spam_trigram("to", "investing", "stocks").
spam_trigram("trade", "in", "stocks").
spam_trigram("in", "stocks", "featured").
spam_trigram("stocks", "featured", "within").
spam_trigram("to", "stop", "future").
spam_trigram("and", "should", "not").
spam_trigram("their", "respective", "owners").
spam_trigram("mg", "30", "pills").
spam_trigram("00", "60", "pills").
spam_trigram("p", "p", "align").
spam_trigram("height", "124", "a").
spam_trigram("1933", "and", "section").
spam_trigram("expectations", "estimates", "and").
spam_trigram("estimates", "and", "projections").
spam_trigram("and", "projections", "at").
spam_trigram("projections", "at", "the").
spam_trigram("the", "time", "the").
spam_trigram("time", "the", "statements").
spam_trigram("the", "statements", "are").
spam_trigram("are", "made", "that").
spam_trigram("of", "risks", "and").
spam_trigram("and", "uncertainties", "which").
spam_trigram("use", "of", "words").
spam_trigram("of", "words", "such").
spam_trigram("words", "such", "as").
spam_trigram("investing", "stocks", "securities").
spam_trigram("stocks", "securities", "must").
spam_trigram("img", "border", "0").
spam_trigram("124", "a", "href").
spam_trigram("http", "www", "china").
spam_trigram("www", "china", "itoy").
spam_trigram("information", "within", "this").
spam_trigram("section", "21", "b").
spam_trigram("of", "1934", "any").
spam_trigram("1934", "any", "statements").
spam_trigram("respect", "to", "predictions").
spam_trigram("or", "performance", "are").
spam_trigram("performance", "are", "not").
spam_trigram("are", "not", "statements").
spam_trigram("not", "statements", "of").
spam_trigram("based", "on", "expectations").
spam_trigram("on", "expectations", "estimates").
spam_trigram("or", "events", "to").
spam_trigram("events", "to", "differ").
spam_trigram("in", "this", "action").
spam_trigram("this", "action", "may").
spam_trigram("action", "may", "be").
spam_trigram("be", "identified", "through").
spam_trigram("identified", "through", "the").
spam_trigram("through", "the", "use").
spam_trigram("such", "as", "projects").
spam_trigram("as", "projects", "foresee").
spam_trigram("projects", "foresee", "expects").
spam_trigram("readers", "and", "subscribers").
spam_trigram("and", "subscribers", "to").
spam_trigram("subscribers", "to", "seek").
spam_trigram("does", "not", "represent").
spam_trigram("a", "registered", "investment").
spam_trigram("future", "looking", "statements").
spam_trigram("respective", "owners", "products").
spam_trigram("owners", "products", "may").
spam_trigram("paliourg", "iit", "demokritos").
spam_trigram("you", "can", "get").
spam_trigram("in", "the", "world").
spam_trigram("be", "able", "to").
spam_trigram("21", "b", "of").
spam_trigram("b", "of", "the").
spam_trigram("discussions", "with", "respect").
spam_trigram("fact", "and", "may").
spam_trigram("or", "that", "by").
spam_trigram("that", "by", "statements").
spam_trigram("by", "statements", "indicating").
spam_trigram("statements", "indicating", "certain").
spam_trigram("indicating", "certain", "actions").
spam_trigram("certain", "actions", "may").
spam_trigram("or", "might", "occur").
spam_trigram("or", "if", "you").
spam_trigram("office", "xp", "professional").
spam_trigram("not", "reply", "to").
spam_trigram("00", "32", "00").
spam_trigram("3", "darial", "color").
spam_trigram("darial", "color", "3").
spam_trigram("nbsp", "td", "td").
spam_trigram("report", "be", "aware").
spam_trigram("aware", "of", "an").
spam_trigram("of", "an", "inherent").
spam_trigram("of", "interest", "resulting").
spam_trigram("interest", "resulting", "from").
spam_trigram("resulting", "from", "such").
spam_trigram("at", "any", "time").
spam_trigram("microsoft", "windows", "xp").
spam_trigram("in", "order", "to").
spam_trigram("p", "align", "3").
spam_trigram("index", "htmlimg", "border").
spam_trigram("htmlimg", "border", "0").
spam_trigram("align", "center", "width").
spam_trigram("plans", "projections", "objectives").
spam_trigram("a", "registered", "professional").
spam_trigram("registered", "professional", "securities").
spam_trigram("professional", "securities", "representative").
spam_trigram("many", "of", "these").
spam_trigram("due", "to", "the").
spam_trigram("wish", "to", "stop").
spam_trigram("you", "want", "to").
spam_trigram("photoshop", "7", "0").
spam_trigram("you", "will", "be").
spam_trigram("face", "verdana", "size").
spam_trigram("width", "124", "height").
spam_trigram("td", "tr", "table").
spam_trigram("com", "hotlist", "hottlist").
spam_trigram("hotlist", "hottlist", "_").
spam_trigram("hottlist", "_", "09").
spam_trigram("future", "events", "or").
spam_trigram("from", "those", "presently").
spam_trigram("those", "presently", "anticipated").
spam_trigram("contained", "in", "this").
spam_trigram("based", "on", "the").
spam_trigram("oi", "and", "gas").
spam_trigram("forward", "ooking", "statements").
spam_trigram("td", "bgcolor", "000000").
spam_trigram("bgcolor", "000000", "align").
spam_trigram("000000", "align", "center").
spam_trigram("center", "width", "124").
spam_trigram("any", "statements", "that").
spam_trigram("statements", "that", "express").
spam_trigram("that", "express", "or").
spam_trigram("assumptions", "or", "future").
spam_trigram("or", "future", "events").
spam_trigram("events", "or", "performance").
spam_trigram("looking", "statements", "are").
spam_trigram("cause", "actual", "results").
spam_trigram("past", "performance", "is").
spam_trigram("click", "here", "for").
spam_trigram("the", "u", "s").
spam_trigram("for", "deals", "your").
spam_trigram("deals", "your", "one").
spam_trigram("no", "thanks", "http").
spam_trigram("cialis", "soft", "tabs").
spam_trigram("99", "90", "pills").
spam_trigram("00", "90", "pills").
spam_trigram("please", "do", "not").
spam_trigram("00", "25", "00").
spam_trigram("00", "20", "00").
spam_trigram("verdana", "size", "1").
spam_trigram("jpg", "width", "120").
spam_trigram("or", "involve", "discussions").
spam_trigram("involve", "discussions", "with").
spam_trigram("expectations", "beliefs", "plans").
spam_trigram("beliefs", "plans", "projections").
spam_trigram("results", "or", "events").
spam_trigram("estimates", "believes", "understands").
spam_trigram("actions", "may", "could").
spam_trigram("may", "could", "or").
spam_trigram("could", "or", "might").
spam_trigram("yahoo", "com", "subject").
spam_trigram("as", "well", "as").
spam_trigram("part", "of", "our").
spam_trigram("january", "2004", "full").
spam_trigram("2004", "full", "story").
spam_trigram("express", "or", "involve").
spam_trigram("may", "be", "forward").
spam_trigram("the", "information", "contained").
spam_trigram("information", "contained", "in").
spam_trigram("investment", "advice", "or").
spam_trigram("in", "this", "report").
spam_trigram("from", "a", "third").
spam_trigram("use", "of", "the").
spam_trigram("one", "stop", "distributorjebel").
spam_trigram("stop", "distributorjebel", "ali").
spam_trigram("distributorjebel", "ali", "duty").
spam_trigram("microsoft", "office", "xp").
spam_trigram("to", "your", "door").
spam_trigram("124", "height", "124").
spam_trigram("width", "120", "height").
spam_trigram("120", "height", "120").
spam_trigram("height", "120", "a").
spam_trigram("120", "a", "td").
spam_trigram("this", "report", "be").
spam_trigram("on", "the", "internet").
spam_trigram("a", "going", "concern").
spam_trigram("the", "pubiisher", "of").
spam_trigram("pubiisher", "of", "this").
spam_trigram("not", "a", "registered").
spam_trigram("indicative", "of", "future").
spam_trigram("the", "fact", "that").
spam_trigram("that", "this", "is").
spam_trigram("is", "a", "paid").
spam_trigram("sales", "department", "for").
spam_trigram("department", "for", "further").
spam_trigram("the", "contents", "of").
spam_trigram("no", "prescription", "required").
spam_trigram("save", "up", "to").
spam_trigram("img", "src", "http").
spam_trigram("tr", "td", "colspan").
spam_trigram("border", "0", "a").
spam_trigram("statements", "of", "historical").
spam_trigram("of", "historical", "fact").
spam_trigram("historical", "fact", "and").
spam_trigram("made", "that", "involve").
spam_trigram("that", "involve", "a").
spam_trigram("involve", "a", "number").
spam_trigram("uncertainties", "which", "could").
spam_trigram("which", "could", "cause").
spam_trigram("could", "cause", "actual").
spam_trigram("this", "newsletter", "is").
spam_trigram("the", "company", "has").
spam_trigram("there", "can", "be").
spam_trigram("can", "be", "no").
spam_trigram("be", "no", "assurance").
spam_trigram("as", "soon", "as").
spam_trigram("99", "our", "low").
spam_trigram("corel", "draw", "graphics").
spam_trigram("draw", "graphics", "suite").
spam_trigram("the", "company", "is").
spam_trigram("you", "for", "your").
spam_trigram("7", "0", "60").
spam_trigram("your", "browser", "subject").
spam_trigram("this", "e", "mail").
spam_trigram("next", "of", "kin").
spam_trigram("here", "to", "be").
spam_trigram("_", "alt", "rnd").
spam_trigram("alt", "rnd", "_").
spam_trigram("td", "td", "bgcolor").
spam_trigram("d", "2", "face").
spam_trigram("2", "face", "3").
spam_trigram("current", "price", "0").
spam_trigram("voice", "over", "internet").
spam_trigram("contains", "forward", "looking").
spam_trigram("be", "forward", "looking").
spam_trigram("actual", "results", "or").
spam_trigram("looking", "statements", "in").
spam_trigram("all", "information", "provided").
spam_trigram("to", "make", "the").
spam_trigram("are", "on", "the").
spam_trigram("this", "report", "is").
spam_trigram("information", "in", "this").
spam_trigram("fact", "that", "this").
spam_trigram("to", "its", "accuracy").
spam_trigram("its", "accuracy", "or").
spam_trigram("your", "acceptance", "of").
spam_trigram("here", "or", "send").
spam_trigram("or", "send", "a").
spam_trigram("if", "you", "don").
spam_trigram("your", "money", "back").
spam_trigram("men", "s", "health").
spam_trigram("contents", "of", "this").
spam_trigram("g", "r", "a").
spam_trigram("flash", "mx", "2004").
spam_trigram("check", "it", "out").
spam_trigram("div", "align", "3").
spam_trigram("looking", "statements", "forward").
spam_trigram("all", "readers", "and").
spam_trigram("this", "report", "shall").
spam_trigram("report", "shall", "be").
spam_trigram("shall", "be", "construed").
spam_trigram("the", "forward", "looking").
spam_trigram("registered", "investment", "advisor").
spam_trigram("not", "represent", "that").
spam_trigram("represent", "that", "the").
spam_trigram("that", "the", "information").
spam_trigram("in", "this", "message").
spam_trigram("this", "message", "states").
spam_trigram("facts", "or", "does").
spam_trigram("or", "does", "not").
spam_trigram("does", "not", "omit").
spam_trigram("not", "omit", "a").
spam_trigram("fact", "necessary", "to").
spam_trigram("necessary", "to", "make").
spam_trigram("make", "the", "statements").
spam_trigram("the", "statements", "therein").
spam_trigram("statements", "therein", "not").
spam_trigram("investment", "advice", "the").
spam_trigram("these", "companies", "are").
spam_trigram("companies", "are", "on").
spam_trigram("on", "the", "verge").
spam_trigram("the", "verge", "of").
spam_trigram("verge", "of", "bankruptcy").
spam_trigram("of", "bankruptcy", "you").
spam_trigram("bankruptcy", "you", "can").
spam_trigram("your", "money", "by").
spam_trigram("money", "by", "investing").
spam_trigram("by", "investing", "in").
spam_trigram("investing", "in", "this").
spam_trigram("not", "view", "information").
spam_trigram("view", "information", "herein").
spam_trigram("information", "herein", "as").
spam_trigram("tax", "accounting", "or").
spam_trigram("accounting", "or", "investment").
spam_trigram("or", "investment", "advice").
spam_trigram("this", "report", "was").
spam_trigram("report", "was", "gathered").
spam_trigram("was", "gathered", "from").
spam_trigram("and", "company", "press").
spam_trigram("not", "an", "officer").
spam_trigram("an", "officer", "director").
spam_trigram("officer", "director", "or").
spam_trigram("from", "such", "compensation").
spam_trigram("such", "compensation", "due").
spam_trigram("compensation", "due", "to").
spam_trigram("to", "the", "fact").
spam_trigram("this", "information", "to").
spam_trigram("information", "to", "be").
spam_trigram("but", "can", "make").
spam_trigram("can", "make", "no").
spam_trigram("as", "to", "its").
spam_trigram("constitutes", "your", "acceptance").
spam_trigram("acceptance", "of", "these").
spam_trigram("of", "these", "terms").
spam_trigram("watch", "this", "one").
spam_trigram("up", "to", "80").
spam_trigram("100", "money", "back").
spam_trigram("money", "back", "guarantee").
spam_trigram("we", "are", "the").
spam_trigram("half", "a", "pill").
spam_trigram("notes", "the", "contents").
spam_trigram("our", "price", "69").
spam_trigram("price", "69", "95").
spam_trigram("3", "d", "ffffffstrongfont").
spam_trigram("align", "center", "bgcolor").
spam_trigram("width", "100", "height").
spam_trigram("9", "pt", "td").
spam_trigram("this", "email", "contains").
spam_trigram("presently", "anticipated", "forward").
spam_trigram("this", "email", "none").
spam_trigram("email", "none", "of").
spam_trigram("as", "with", "many").
spam_trigram("in", "this", "stock").
spam_trigram("no", "assurance", "of").
spam_trigram("assurance", "of", "that").
spam_trigram("of", "that", "happening").
spam_trigram("this", "one", "trade").
spam_trigram("the", "featured", "company").
spam_trigram("our", "low", "price").
spam_trigram("united", "states", "dollars").
spam_trigram("a", "g", "r").
spam_trigram("you", "do", "not").
spam_trigram("up", "to", "36").
spam_trigram("to", "36", "hours").
spam_trigram("under", "your", "tongue").
spam_trigram("99", "120", "pills").
spam_trigram("pills", "149", "00").
spam_trigram("htmlimg", "src", "http").
spam_trigram("be", "removed", "subject").
spam_trigram("a", "td", "tr").
spam_trigram("font", "face", "verdana").
spam_trigram("anticipated", "forward", "looking").
spam_trigram("this", "email", "pertaining").
spam_trigram("email", "pertaining", "to").
spam_trigram("advises", "all", "readers").
spam_trigram("section", "17", "b").
spam_trigram("about", "the", "company").
spam_trigram("to", "continue", "as").
spam_trigram("continue", "as", "a").
spam_trigram("as", "a", "going").
spam_trigram("this", "stock", "the").
spam_trigram("investment", "advice", "any").
spam_trigram("advice", "any", "reference").
spam_trigram("any", "reference", "to").
spam_trigram("reference", "to", "past").
spam_trigram("of", "companies", "are").
spam_trigram("to", "be", "referenced").
spam_trigram("be", "referenced", "based").
spam_trigram("referenced", "based", "on").
spam_trigram("performance", "of", "these").
spam_trigram("these", "companies", "you").
spam_trigram("need", "perfect", "timing").
spam_trigram("perfect", "timing", "to").
spam_trigram("given", "there", "can").
spam_trigram("that", "happening", "remember").
spam_trigram("happening", "remember", "as").
spam_trigram("of", "future", "results").
spam_trigram("and", "a", "thorough").
spam_trigram("a", "thorough", "due").
spam_trigram("prior", "to", "investing").
spam_trigram("to", "company", "websites").
spam_trigram("the", "receipt", "of").
spam_trigram("graphics", "suite", "11").
spam_trigram("not", "limited", "to").
spam_trigram("stop", "future", "mailings").
spam_trigram("remove", "your", "email").
spam_trigram("term", "target", "price").
spam_trigram("to", "this", "message").
spam_trigram("military", "sources", "said").
spam_trigram("i", "a", "g").
spam_trigram("china", "world", "trade").
spam_trigram("send", "a", "blank").
spam_trigram("fontfont", "color", "3").
spam_trigram("style", "font", "size").
spam_trigram("font", "td", "tr").
spam_trigram("td", "valign", "top").
spam_trigram("_", "09", "htmlimg").
spam_trigram("09", "htmlimg", "src").
spam_trigram("index", "php", "s").
spam_trigram("00", "90", "pi").
spam_trigram("90", "pi", "lls").
spam_trigram("over", "internet", "protocol").
spam_trigram("statements", "forward", "looking").
spam_trigram("the", "news", "release").
spam_trigram("and", "uncertainties", "that").
spam_trigram("results", "to", "differ").
spam_trigram("from", "those", "set").
spam_trigram("those", "set", "forth").
spam_trigram("set", "forth", "in").
spam_trigram("in", "the", "forward").
spam_trigram("of", "the", "private").
spam_trigram("to", "predictions", "expectations").
spam_trigram("future", "ooking", "statements").
spam_trigram("understands", "or", "that").
spam_trigram("a", "review", "of").
spam_trigram("review", "of", "a").
spam_trigram("third", "party", "not").
spam_trigram("party", "not", "an").
spam_trigram("in", "our", "membership").
spam_trigram("with", "no", "thanks").
spam_trigram("no", "thanks", "in").
spam_trigram("thanks", "in", "the").
spam_trigram("for", "you", "to").
spam_trigram("products", "and", "services").
spam_trigram("but", "not", "limited").
spam_trigram("accuracy", "or", "completeness").
spam_trigram("v", "i", "a").
spam_trigram("there", "is", "a").
spam_trigram("please", "click", "here").
spam_trigram("if", "you", "would").
spam_trigram("9", "pt", "colspan").
spam_trigram("9", "pt", "valign").
spam_trigram("pt", "valign", "middle").
spam_trigram("there", "is", "no").
spam_trigram("internet", "protocol", "voip").
spam_trigram("email", "contains", "forward").
spam_trigram("there", "is", "an").
spam_trigram("statements", "and", "opinions").
spam_trigram("that", "could", "cause").
spam_trigram("the", "private", "securities").
spam_trigram("private", "securities", "litigation").
spam_trigram("securities", "litigation", "reform").
spam_trigram("litigation", "reform", "act").
spam_trigram("reform", "act", "of").
spam_trigram("act", "of", "1995").
spam_trigram("some", "of", "the").
spam_trigram("with", "many", "microcap").
spam_trigram("many", "microcap", "stocks").
spam_trigram("today", "s", "company").
spam_trigram("s", "company", "has").
spam_trigram("of", "a", "company").
spam_trigram("including", "but", "not").
spam_trigram("believes", "this", "information").
spam_trigram("don", "t", "want").
spam_trigram("all", "your", "money").
spam_trigram("your", "email", "subject").
spam_trigram("no", "prior", "prescription").
spam_trigram("this", "is", "an").
spam_trigram("easy", "to", "use").
spam_trigram("you", "can", "do").
spam_trigram("charset", "us", "ascii").
spam_trigram("content", "transfer", "encoding").
spam_trigram("_", "i", "_").
spam_trigram("for", "the", "best").
spam_trigram("and", "paste", "this").
spam_trigram("paste", "this", "link").
spam_trigram("this", "link", "into").
spam_trigram("link", "into", "your").
spam_trigram("at", "http", "www").
spam_trigram("this", "message", "this").
spam_trigram("align", "3", "dcenterfont").
spam_trigram("tr", "td", "height").
spam_trigram("_", "cf", "index").
spam_trigram("pt", "td", "td").
spam_trigram("publication", "of", "this").
spam_trigram("is", "an", "inherent").
spam_trigram("statements", "which", "are").
spam_trigram("forth", "in", "the").
spam_trigram("meaning", "of", "the").
spam_trigram("and", "intend", "or").
spam_trigram("stocks", "today", "s").
spam_trigram("omit", "a", "material").
spam_trigram("a", "material", "fact").
spam_trigram("material", "fact", "necessary").
spam_trigram("sources", "including", "but").
spam_trigram("company", "press", "releases").
spam_trigram("the", "subject", "to").
spam_trigram("your", "browser", "please").
spam_trigram("browser", "please", "give").
spam_trigram("please", "give", "it").
spam_trigram("give", "it", "atleast").
spam_trigram("it", "atleast", "48").
spam_trigram("atleast", "48", "hours").
spam_trigram("48", "hours", "for").
spam_trigram("hours", "for", "unsubscription").
spam_trigram("for", "unsubscription", "to").
spam_trigram("unsubscription", "to", "be").
spam_trigram("to", "be", "effective").
spam_trigram("be", "effective", "subject").
spam_trigram("here", "for", "more").
spam_trigram("in", "the", "u").
spam_trigram("director", "or", "affiliate").
spam_trigram("with", "the", "securities").
spam_trigram("and", "is", "not").
spam_trigram("sent", "you", "an").
spam_trigram("you", "an", "email").
spam_trigram("802", "11", "g").
spam_trigram("the", "price", "of").
spam_trigram("one", "of", "our").
spam_trigram("as", "little", "as").
spam_trigram("the", "link", "below").
spam_trigram("get", "your", "money").
spam_trigram("mix", "alcohol", "drinks").
spam_trigram("alcohol", "drinks", "with").
spam_trigram("a", "pill", "under").
spam_trigram("pill", "under", "your").
spam_trigram("your", "tongue", "10").
spam_trigram("tongue", "10", "min").
spam_trigram("10", "min", "before").
spam_trigram("also", "have", "less").
spam_trigram("have", "less", "sidebacks").
spam_trigram("less", "sidebacks", "you").
spam_trigram("sidebacks", "you", "can").
spam_trigram("you", "can", "drive").
spam_trigram("can", "drive", "or").
spam_trigram("drive", "or", "mix").
spam_trigram("or", "mix", "alcohol").
spam_trigram("apple", "macintosh", "our").
spam_trigram("macintosh", "our", "price").
spam_trigram("windows", "xp", "pro").
spam_trigram("99", "our", "price").
spam_trigram("your", "claims", "agent").
spam_trigram("cf", "index", "htmlimg").
spam_trigram("br", "br", "br").
spam_trigram("font", "font", "strong").
spam_trigram("100", "height", "100").
spam_trigram("_", "ftar", "index").
spam_trigram("itoy", "com", "email").
spam_trigram("2003", "indianapolis", "in").
spam_trigram("our", "intent", "to").
spam_trigram("interest", "in", "our").
spam_trigram("which", "are", "based").
spam_trigram("based", "on", "certain").
spam_trigram("on", "certain", "assumptions").
spam_trigram("certain", "assumptions", "and").
spam_trigram("uncertainties", "that", "could").
spam_trigram("be", "advised", "that").
spam_trigram("only", "and", "should").
spam_trigram("inc", "is", "a").
spam_trigram("predictions", "expectations", "beliefs").
spam_trigram("are", "subject", "to").
spam_trigram("of", "the", "materia").
spam_trigram("the", "materia", "within").
spam_trigram("materia", "within", "this").
spam_trigram("you", "can", "lose").
spam_trigram("to", "past", "performance").
spam_trigram("past", "performance", "s").
spam_trigram("performance", "s", "of").
spam_trigram("s", "of", "companies").
spam_trigram("performance", "is", "not").
spam_trigram("thorough", "due", "diligence").
spam_trigram("due", "diligence", "effort").
spam_trigram("a", "company", "s").
spam_trigram("press", "releases", "the").
spam_trigram("terms", "if", "you").
spam_trigram("if", "you", "feel").
spam_trigram("you", "feel", "you").
spam_trigram("feel", "you", "have").
spam_trigram("go", "here", "or").
spam_trigram("many", "of", "you").
spam_trigram("in", "any", "way").
spam_trigram("xp", "professional", "2002").
spam_trigram("don", "t", "have").
spam_trigram("stock", "the", "publisher").
spam_trigram("effort", "including", "a").
spam_trigram("including", "a", "review").
spam_trigram("be", "completed", "prior").
spam_trigram("completed", "prior", "to").
spam_trigram("limited", "to", "company").
spam_trigram("thousand", "dollars", "from").
spam_trigram("or", "affiliate", "shareholder").
spam_trigram("future", "mailings", "or").
spam_trigram("mailings", "or", "if").
spam_trigram("all", "natural", "adipren").
spam_trigram("this", "is", "the").
spam_trigram("here", "http", "www").
spam_trigram("to", "your", "account").
spam_trigram("for", "more", "information").
spam_trigram("rr", "php", "subject").
spam_trigram("belize", "city", "belize").
spam_trigram("do", "you", "want").
spam_trigram("acts", "up", "to").
spam_trigram("face", "comic", "sans").
spam_trigram("soft", "tabs", "is").
spam_trigram("tabs", "is", "the").
spam_trigram("content", "type", "text").
spam_trigram("terms", "as", "expect").
spam_trigram("to", "confirm", "your").
spam_trigram("adobe", "photoshop", "cs").
spam_trigram("microsoft", "office", "2003").
spam_trigram("00", "40", "00").
spam_trigram("server", "windows", "2000").
spam_trigram("is", "not", "an").
spam_trigram("your", "email", "address").
spam_trigram("align", "3", "dcenter").
spam_trigram("font", "p", "p").

% Top ham trigrams
ham_trigram("hou", "ect", "ect").
ham_trigram("ect", "ect", "cc").
ham_trigram("_", "_", "_").
ham_trigram("corp", "enron", "enron").
ham_trigram("let", "me", "know").
ham_trigram("hou", "ect", "on").
ham_trigram("daren", "j", "farmer").
ham_trigram("ect", "ect", "subject").
ham_trigram("ect", "cc", "subject").
ham_trigram("j", "farmer", "hou").
ham_trigram("farmer", "hou", "ect").
ham_trigram("if", "you", "have").
ham_trigram("you", "have", "any").
ham_trigram("see", "attached", "file").
ham_trigram("original", "message", "from").
ham_trigram("have", "any", "questions").
ham_trigram("please", "let", "me").
ham_trigram("me", "know", "if").
ham_trigram("cc", "subject", "re").
ham_trigram("enron", "enron", "cc").
ham_trigram("enron", "north", "america").
ham_trigram("corp", "enron", "on").
ham_trigram("know", "if", "you").
ham_trigram("vance", "l", "taylor").
ham_trigram("robert", "e", "lloyd").
ham_trigram("north", "america", "corp").
ham_trigram("robert", "cotten", "hou").
ham_trigram("cotten", "hou", "ect").
ham_trigram("america", "corp", "from").
ham_trigram("ect", "subject", "re").
ham_trigram("2000", "teco", "tap").
ham_trigram("to", "daren", "j").
ham_trigram("pat", "clynes", "corp").
ham_trigram("clynes", "corp", "enron").
ham_trigram("hpl", "nom", "for").
ham_trigram("ami", "chokshi", "corp").
ham_trigram("chokshi", "corp", "enron").
ham_trigram("smith", "hou", "ect").
ham_trigram("na", "enron", "enron").
ham_trigram("subject", "hpl", "nom").
ham_trigram("melissa", "graves", "hou").
ham_trigram("graves", "hou", "ect").
ham_trigram("we", "need", "to").
ham_trigram("gcs", "cec", "pec").
ham_trigram("cec", "pec", "pec").
ham_trigram("enron", "hpl", "actuals").
ham_trigram("hpl", "actuals", "for").
ham_trigram("e", "lloyd", "hou").
ham_trigram("lloyd", "hou", "ect").
ham_trigram("enron", "com", "cc").
ham_trigram("subject", "enron", "hpl").
ham_trigram("texas", "utilities", "tu").
ham_trigram("gary", "a", "hanks").
ham_trigram("howard", "b", "camp").
ham_trigram("subject", "re", "meter").
ham_trigram("pefs", "pec", "pec").
ham_trigram("julie", "meyers", "hou").
ham_trigram("meyers", "hou", "ect").
ham_trigram("enron", "enron", "subject").
ham_trigram("enron", "cc", "subject").
ham_trigram("ect", "ect", "pat").
ham_trigram("i", "don", "t").
ham_trigram("taylor", "hou", "ect").
ham_trigram("b", "camp", "hou").
ham_trigram("camp", "hou", "ect").
ham_trigram("forwarded", "by", "ami").
ham_trigram("by", "ami", "chokshi").
ham_trigram("l", "taylor", "hou").
ham_trigram("com", "cc", "subject").
ham_trigram("gco", "enron", "enron").
ham_trigram("any", "questions", "please").
ham_trigram("this", "is", "a").
ham_trigram("ect", "pat", "clynes").
ham_trigram("aimee", "lannou", "hou").
ham_trigram("lannou", "hou", "ect").
ham_trigram("the", "month", "of").
ham_trigram("farmer", "daren", "j").
ham_trigram("would", "like", "to").
ham_trigram("ect", "ect", "robert").
ham_trigram("000", "mmbtu", "d").
ham_trigram("2000", "see", "attached").
ham_trigram("ect", "daren", "j").
ham_trigram("fuels", "cotton", "valley").
ham_trigram("hpl", "gas", "daily").
ham_trigram("ect", "ect", "daren").
ham_trigram("if", "you", "need").
ham_trigram("rita", "wynne", "hou").
ham_trigram("wynne", "hou", "ect").
ham_trigram("needs", "to", "be").
ham_trigram("a", "hanks", "hou").
ham_trigram("hanks", "hou", "ect").
ham_trigram("based", "on", "the").
ham_trigram("jackie", "young", "hou").
ham_trigram("young", "hou", "ect").
ham_trigram("george", "weissman", "hou").
ham_trigram("weissman", "hou", "ect").
ham_trigram("donald", "p", "reinhardt").
ham_trigram("ls", "hpl", "lsk").
ham_trigram("ect", "ect", "mary").
ham_trigram("pm", "to", "daren").
ham_trigram("2001", "see", "attached").
ham_trigram("ect", "melissa", "graves").
ham_trigram("ect", "on", "03").
ham_trigram("ect", "ect", "melissa").
ham_trigram("30", "000", "enron").
ham_trigram("if", "hsc", "less").
ham_trigram("hpl", "lsk", "ic").
ham_trigram("hsc", "less", "0").
ham_trigram("carlos", "j", "rodriguez").
ham_trigram("for", "the", "month").
ham_trigram("will", "need", "to").
ham_trigram("i", "need", "to").
ham_trigram("as", "soon", "as").
ham_trigram("be", "able", "to").
ham_trigram("susan", "smith", "hou").
ham_trigram("i", "will", "be").
ham_trigram("created", "and", "entered").
ham_trigram("lee", "l", "papayoti").
ham_trigram("there", "is", "a").
ham_trigram("attached", "file", "hplno").
ham_trigram("from", "fuels", "cotton").
ham_trigram("to", "robert", "cotten").
ham_trigram("vlt", "x", "3").
ham_trigram("x", "3", "6353").
ham_trigram("of", "the", "month").
ham_trigram("000", "enron", "subject").
ham_trigram("pm", "to", "robert").
ham_trigram("brenda", "f", "herod").
ham_trigram("cc", "daren", "j").
ham_trigram("lauri", "a", "allen").
ham_trigram("please", "call", "me").
ham_trigram("100", "if", "hsc").
ham_trigram("ect", "ect", "susan").
ham_trigram("forwarded", "by", "robert").
ham_trigram("mmbtu", "d", "100").
ham_trigram("p", "reinhardt", "hou").
ham_trigram("reinhardt", "hou", "ect").
ham_trigram("calpine", "daily", "gas").
ham_trigram("daily", "gas", "nomination").
ham_trigram("melissa", "jones", "texas").
ham_trigram("jones", "texas", "utilities").
ham_trigram("on", "the", "following").
ham_trigram("tom", "acton", "corp").
ham_trigram("acton", "corp", "enron").
ham_trigram("ect", "ect", "howard").
ham_trigram("ect", "howard", "b").
ham_trigram("am", "to", "daren").
ham_trigram("lsp", "enserch", "us").
ham_trigram("need", "to", "be").
ham_trigram("dfarmer", "enron", "com").
ham_trigram("ect", "ect", "lisa").
ham_trigram("xls", "subject", "re").
ham_trigram("gary", "w", "lamphier").
ham_trigram("000", "hpl", "iferc").
ham_trigram("thank", "you", "for").
ham_trigram("f", "herod", "hou").
ham_trigram("herod", "hou", "ect").
ham_trigram("attached", "file", "hplo").
ham_trigram("ect", "on", "05").
ham_trigram("lisa", "hesse", "hou").
ham_trigram("hesse", "hou", "ect").
ham_trigram("thanks", "vlt", "x").
ham_trigram("allen", "hou", "ect").
ham_trigram("this", "is", "the").
ham_trigram("enron", "subject", "re").
ham_trigram("the", "end", "of").
ham_trigram("actual", "flow", "for").
ham_trigram("enserch", "us", "tu").
ham_trigram("ect", "ect", "donald").
ham_trigram("ect", "donald", "p").
ham_trigram("to", "cc", "subject").
ham_trigram("a", "allen", "hou").
ham_trigram("i", "would", "like").
ham_trigram("ect", "on", "08").
ham_trigram("easttexas", "pefs", "pec").
ham_trigram("charlie", "stone", "texas").
ham_trigram("stone", "texas", "utilities").
ham_trigram("ect", "ect", "gary").
ham_trigram("ect", "cc", "daren").
ham_trigram("ect", "susan", "smith").
ham_trigram("in", "order", "to").
ham_trigram("l", "papayoti", "hou").
ham_trigram("papayoti", "hou", "ect").
ham_trigram("me", "know", "what").
ham_trigram("david", "avila", "lsp").
ham_trigram("avila", "lsp", "enserch").
ham_trigram("subject", "tenaska", "iv").
ham_trigram("redeliveries", "will", "be").
ham_trigram("luong", "hou", "ect").
ham_trigram("anita", "luong", "hou").
ham_trigram("20", "000", "enron").
ham_trigram("as", "well", "as").
ham_trigram("will", "not", "be").
ham_trigram("out", "of", "the").
ham_trigram("tu", "charlie", "stone").
ham_trigram("at", "this", "meter").
ham_trigram("w", "lamphier", "hou").
ham_trigram("lamphier", "hou", "ect").
ham_trigram("pm", "enron", "north").
ham_trigram("to", "david", "avila").
ham_trigram("us", "tu", "charlie").
ham_trigram("tu", "melissa", "jones").
ham_trigram("gpgfin", "enron", "enron").
ham_trigram("enron", "enronxgate", "on").
ham_trigram("ect", "on", "01").
ham_trigram("brian", "m", "riley").
ham_trigram("reliantenergy", "com", "on").
ham_trigram("jackie", "3", "9497").
ham_trigram("ect", "on", "04").
ham_trigram("all", "of", "the").
ham_trigram("if", "you", "are").
ham_trigram("am", "to", "robert").
ham_trigram("any", "questions", "or").
ham_trigram("you", "want", "to").
ham_trigram("sherlyn", "schumack", "hou").
ham_trigram("schumack", "hou", "ect").
ham_trigram("noms", "actual", "flow").
ham_trigram("m", "riley", "hou").
ham_trigram("riley", "hou", "ect").
ham_trigram("albrecht", "4", "well").
ham_trigram("eileen", "ponton", "on").
ham_trigram("liz", "bellamy", "enron").
ham_trigram("bellamy", "enron", "com").
ham_trigram("entered", "into", "sitara").
ham_trigram("mary", "m", "smith").
ham_trigram("ect", "ect", "michael").
ham_trigram("rodriguez", "hou", "ect").
ham_trigram("am", "to", "david").
ham_trigram("cynthia", "hakemack", "hou").
ham_trigram("hakemack", "hou", "ect").
ham_trigram("m", "smith", "hou").
ham_trigram("david", "baumbach", "hou").
ham_trigram("baumbach", "hou", "ect").
ham_trigram("thanks", "for", "your").
ham_trigram("enron", "com", "subject").
ham_trigram("mmbtu", "per", "day").
ham_trigram("for", "your", "help").
ham_trigram("questions", "please", "call").
ham_trigram("utilities", "tu", "melissa").
ham_trigram("j", "rodriguez", "hou").
ham_trigram("from", "robert", "e").
ham_trigram("megan", "parker", "corp").
ham_trigram("parker", "corp", "enron").
ham_trigram("ect", "on", "06").
ham_trigram("am", "enron", "north").
ham_trigram("me", "know", "thanks").
ham_trigram("hpl", "scheduling", "enron").
ham_trigram("scheduling", "enron", "com").
ham_trigram("into", "sitara", "based").
ham_trigram("sitara", "based", "on").
ham_trigram("ect", "ect", "george").
ham_trigram("ect", "on", "07").
ham_trigram("bob", "forwarded", "by").
ham_trigram("give", "me", "a").
ham_trigram("to", "aimee", "lannou").
ham_trigram("d", "100", "if").
ham_trigram("soon", "as", "possible").
ham_trigram("enron", "com", "liz").
ham_trigram("com", "liz", "bellamy").
ham_trigram("000", "hpl", "gas").
ham_trigram("to", "jackie", "young").
ham_trigram("can", "you", "please").
ham_trigram("and", "should", "be").
ham_trigram("please", "see", "the").
ham_trigram("hou", "ect", "enron").
ham_trigram("coastal", "oil", "gas").
ham_trigram("the", "gathering", "contract").
ham_trigram("in", "the", "system").
ham_trigram("the", "redeliveries", "will").
ham_trigram("this", "e", "mail").
ham_trigram("subject", "re", "deal").
ham_trigram("could", "you", "please").
ham_trigram("attached", "is", "the").
ham_trigram("thanks", "megan", "subject").
ham_trigram("3", "6353", "subject").
ham_trigram("by", "robert", "cotten").
ham_trigram("to", "robert", "e").
ham_trigram("call", "me", "at").
ham_trigram("tu", "hpl", "scheduling").
ham_trigram("should", "be", "created").
ham_trigram("be", "created", "and").
ham_trigram("attached", "to", "the").
ham_trigram("to", "the", "gathering").
ham_trigram("see", "the", "attached").
ham_trigram("any", "questions", "thanks").
ham_trigram("ect", "ect", "james").
ham_trigram("me", "a", "call").
ham_trigram("feel", "free", "to").
ham_trigram("enron", "_", "development").
ham_trigram("utilities", "tu", "hpl").
ham_trigram("attached", "file", "hplnl").
ham_trigram("and", "entered", "into").
ham_trigram("to", "ami", "chokshi").
ham_trigram("will", "have", "to").
ham_trigram("forwarded", "by", "gary").
ham_trigram("ticket", "should", "be").
ham_trigram("ect", "ect", "vance").
ham_trigram("ect", "lisa", "hesse").
ham_trigram("in", "the", "im").
ham_trigram("the", "im", "wellhead").
ham_trigram("im", "wellhead", "portfolio").
ham_trigram("ect", "on", "02").
ham_trigram("ect", "vance", "l").
ham_trigram("let", "you", "know").
ham_trigram("we", "will", "be").
ham_trigram("and", "let", "me").
ham_trigram("000", "mmbtu", "per").
ham_trigram("meter", "098", "4179").
ham_trigram("am", "to", "ami").
ham_trigram("am", "to", "cc").
ham_trigram("a", "copy", "of").
ham_trigram("don", "t", "know").
ham_trigram("sales", "on", "hpl").
ham_trigram("should", "be", "tracked").
ham_trigram("be", "tracked", "in").
ham_trigram("tracked", "in", "the").
ham_trigram("wellhead", "portfolio", "attached").
ham_trigram("portfolio", "attached", "to").
ham_trigram("fred", "boas", "hou").
ham_trigram("some", "of", "the").
ham_trigram("the", "following", "information").
ham_trigram("will", "continue", "to").
ham_trigram("fyi", "forwarded", "by").
ham_trigram("ect", "ect", "rita").
ham_trigram("do", "not", "have").
ham_trigram("j", "farmer", "enron").
ham_trigram("iferc", "ls", "hpl").
ham_trigram("attached", "file", "hpl").
ham_trigram("to", "julie", "meyers").
ham_trigram("thanks", "jackie", "3").
ham_trigram("ect", "rita", "wynne").
ham_trigram("morris", "hou", "ect").
ham_trigram("enron", "on", "06").
ham_trigram("000", "mmbtu", "dy").
ham_trigram("oil", "gas", "corporation").
ham_trigram("mckay", "hou", "ect").
ham_trigram("mary", "poorman", "na").
ham_trigram("poorman", "na", "enron").
ham_trigram("subject", "eastrans", "nomination").
ham_trigram("to", "unaccounted", "for").
ham_trigram("unaccounted", "for", "gas").
ham_trigram("are", "as", "follows").
ham_trigram("july", "2000", "activity").
ham_trigram("ect", "subject", "meter").
ham_trigram("houston", "pefs", "pec").
ham_trigram("to", "d", "h").
ham_trigram("here", "is", "the").
ham_trigram("that", "i", "can").
ham_trigram("subject", "calpine", "daily").
ham_trigram("of", "the", "office").
ham_trigram("ect", "cc", "robert").
ham_trigram("00", "463", "2").
ham_trigram("james", "mckay", "hou").
ham_trigram("hpl", "iferc", "ls").
ham_trigram("gas", "nomination", "1").
ham_trigram("nomination", "1", "doc").
ham_trigram("00", "00", "pm").
ham_trigram("stella", "l", "morris").
ham_trigram("clem", "cernosek", "hou").
ham_trigram("cernosek", "hou", "ect").
ham_trigram("ect", "ect", "steve").
ham_trigram("know", "what", "you").
ham_trigram("please", "do", "not").
ham_trigram("teco", "tap", "30").
ham_trigram("tap", "30", "000").
ham_trigram("a", "list", "of").
ham_trigram("ect", "on", "12").
ham_trigram("ect", "ect", "julie").
ham_trigram("please", "feel", "free").
ham_trigram("00", "00", "am").
ham_trigram("sat", "11", "3").
ham_trigram("11", "3", "2001").
ham_trigram("3", "2001", "at").
ham_trigram("been", "created", "and").
ham_trigram("gas", "from", "the").
ham_trigram("to", "set", "up").
ham_trigram("katherine", "herrera", "corp").
ham_trigram("herrera", "corp", "enron").
ham_trigram("forwarded", "by", "george").
ham_trigram("marta", "k", "henderson").
ham_trigram("one", "of", "the").
ham_trigram("subject", "noms", "actual").
ham_trigram("entered", "in", "sitara").
ham_trigram("cc", "pat", "clynes").
ham_trigram("houston", "texas", "77002").
ham_trigram("to", "lee", "l").
ham_trigram("into", "pg", "e").
ham_trigram("subject", "re", "fw").
ham_trigram("08", "09", "2000").
ham_trigram("i", "spoke", "with").
ham_trigram("ect", "ect", "scott").
ham_trigram("if", "there", "is").
ham_trigram("and", "entered", "in").
ham_trigram("of", "the", "deal").
ham_trigram("hou", "ees", "ees").
ham_trigram("ect", "gary", "a").
ham_trigram("stephanie", "gomes", "hou").
ham_trigram("gomes", "hou", "ect").
ham_trigram("chokshi", "enron", "com").
ham_trigram("daren", "j", "subject").
ham_trigram("ect", "on", "11").
ham_trigram("and", "i", "will").
ham_trigram("j", "farmer", "ect").
ham_trigram("ect", "julie", "meyers").
ham_trigram("kristen", "j", "hanson").
ham_trigram("forwarded", "by", "aimee").
ham_trigram("by", "aimee", "lannou").
ham_trigram("1", "00", "production").
ham_trigram("d", "h", "gas").
ham_trigram("h", "gas", "company").
ham_trigram("end", "of", "the").
ham_trigram("cc", "subject", "noms").
ham_trigram("ect", "ect", "cynthia").
ham_trigram("40", "000", "enron").
ham_trigram("volumes", "to", "unaccounted").
ham_trigram("meter", "1266", "july").
ham_trigram("1266", "july", "2000").
ham_trigram("2000", "activity", "allocation").
ham_trigram("activity", "allocation", "exception").
ham_trigram("nguyen", "hou", "ect").
ham_trigram("in", "addition", "to").
ham_trigram("to", "make", "sure").
ham_trigram("edward", "terry", "hou").
ham_trigram("terry", "hou", "ect").
ham_trigram("if", "this", "is").
ham_trigram("thanks", "forwarded", "by").
ham_trigram("if", "there", "are").
ham_trigram("ect", "mary", "m").
ham_trigram("o", "neal", "d").
ham_trigram("lisa", "csikos", "hou").
ham_trigram("csikos", "hou", "ect").
ham_trigram("so", "that", "i").
ham_trigram("cc", "subject", "meter").
ham_trigram("for", "tenaska", "iv").
ham_trigram("attached", "is", "a").
ham_trigram("do", "you", "want").
ham_trigram("i", "have", "a").
ham_trigram("ricky", "a", "archer").
ham_trigram("a", "archer", "fuel").
ham_trigram("archer", "fuel", "supply").
ham_trigram("fuel", "supply", "700").
ham_trigram("supply", "700", "louisiana").
ham_trigram("700", "louisiana", "suite").
ham_trigram("louisiana", "suite", "2700").
ham_trigram("suite", "2700", "houston").
ham_trigram("2700", "houston", "texas").
ham_trigram("texas", "77002", "713").
ham_trigram("77002", "713", "830").
ham_trigram("713", "830", "8659").
ham_trigram("830", "8659", "direct").
ham_trigram("8659", "direct", "713").
ham_trigram("direct", "713", "830").
ham_trigram("713", "830", "8722").
ham_trigram("830", "8722", "fax").
ham_trigram("houston", "pipe", "line").
ham_trigram("deliveries", "to", "eastrans").
ham_trigram("ect", "robert", "e").
ham_trigram("mark", "mccoy", "corp").
ham_trigram("mccoy", "corp", "enron").
ham_trigram("lsk", "ic", "30").
ham_trigram("ic", "30", "000").
ham_trigram("do", "you", "have").
ham_trigram("subject", "re", "coastal").
ham_trigram("need", "to", "get").
ham_trigram("ena", "gas", "sales").
ham_trigram("goliad", "co", "tx").
ham_trigram("ect", "cynthia", "hakemack").
ham_trigram("term", "of", "the").
ham_trigram("gathering", "contract", "thanks").
ham_trigram("ect", "ect", "david").
ham_trigram("j", "rodriguez", "enron").
ham_trigram("rodriguez", "enron", "com").
ham_trigram("don", "t", "have").
ham_trigram("1", "doc", "subject").
ham_trigram("if", "you", "want").
ham_trigram("at", "the", "meter").
ham_trigram("by", "daren", "j").
ham_trigram("enron", "on", "03").
ham_trigram("pm", "to", "aimee").
ham_trigram("4179", "goliad", "co").
ham_trigram("i", "am", "not").
ham_trigram("l", "morris", "hou").
ham_trigram("btu", "1", "027").
ham_trigram("gas", "daily", "ls").
ham_trigram("daily", "ls", "hpl").
ham_trigram("ect", "ect", "lauri").
ham_trigram("ect", "lauri", "a").
ham_trigram("boas", "hou", "ect").
ham_trigram("com", "carlos", "j").
ham_trigram("ect", "cc", "pat").
ham_trigram("a", "new", "deal").
ham_trigram("message", "from", "farmer").
ham_trigram("from", "farmer", "daren").
ham_trigram("beverly", "beaty", "hou").
ham_trigram("beaty", "hou", "ect").
ham_trigram("enron", "capital", "trade").
ham_trigram("capital", "trade", "resources").
ham_trigram("trade", "resources", "corp").
ham_trigram("resources", "corp", "from").
ham_trigram("we", "have", "a").
ham_trigram("j", "hanson", "hou").
ham_trigram("hanson", "hou", "ect").
ham_trigram("extend", "the", "deal").
ham_trigram("85", "if", "hsc").
ham_trigram("part", "of", "the").
ham_trigram("earl", "tisdale", "hou").
ham_trigram("tisdale", "hou", "ect").
ham_trigram("enron", "com", "carlos").
ham_trigram("stacey", "neuweiler", "hou").
ham_trigram("neuweiler", "hou", "ect").
ham_trigram("8722", "fax", "calpine").
ham_trigram("gas", "daily", "less").
ham_trigram("daren", "j", "sent").
ham_trigram("subject", "re", "noms").
ham_trigram("sandi", "m", "braband").
ham_trigram("forwarded", "by", "daren").
ham_trigram("for", "all", "of").
ham_trigram("30", "000", "mmbtu").
ham_trigram("nominates", "the", "following").
ham_trigram("06", "28", "2000").
ham_trigram("to", "get", "the").
ham_trigram("for", "december", "2000").
ham_trigram("on", "hpl", "to").
ham_trigram("by", "george", "weissman").
ham_trigram("1", "027", "subject").
ham_trigram("ect", "ect", "donna").
ham_trigram("please", "note", "that").
ham_trigram("pm", "to", "julie").
ham_trigram("i", "have", "been").
ham_trigram("you", "will", "be").
ham_trigram("edward", "d", "gottlob").
ham_trigram("ftworth", "pefs", "pec").
ham_trigram("ect", "on", "09").
ham_trigram("requirements", "for", "the").
ham_trigram("10", "000", "mmbtu").
ham_trigram("it", "is", "a").
ham_trigram("i", "do", "not").
ham_trigram("we", "don", "t").
ham_trigram("march", "2001", "invoice").
ham_trigram("set", "up", "for").
ham_trigram("meter", "0986725", "1").
ham_trigram("0986725", "1", "00").
ham_trigram("enron", "ls", "hpl").
ham_trigram("gas", "corporation", "albrecht").
ham_trigram("corporation", "albrecht", "4").
ham_trigram("4", "well", "meter").
ham_trigram("well", "meter", "098").
ham_trigram("098", "4179", "goliad").
ham_trigram("the", "following", "counterparty").
ham_trigram("nom", "mcf", "mmbtu").
ham_trigram("i", "have", "attached").
ham_trigram("enron", "com", "sent").
ham_trigram("will", "be", "out").
ham_trigram("ect", "ect", "mark").
ham_trigram("enron", "enron", "daren").
ham_trigram("enron", "daren", "j").
ham_trigram("victor", "lamadrid", "hou").
ham_trigram("lamadrid", "hou", "ect").
ham_trigram("to", "the", "plant").
ham_trigram("at", "this", "point").
ham_trigram("me", "if", "you").
ham_trigram("01", "ena", "gas").
ham_trigram("gas", "sales", "on").
ham_trigram("hpl", "to", "d").
ham_trigram("ect", "ect", "stephanie").
ham_trigram("i", "m", "not").
ham_trigram("daily", "less", "0").
ham_trigram("we", "agree", "eileen").
ham_trigram("agree", "eileen", "ponton").
ham_trigram("eastrans", "nomination", "change").
ham_trigram("make", "sure", "that").
ham_trigram("to", "look", "at").
ham_trigram("chad", "w", "cass").
ham_trigram("william", "e", "speckels").
ham_trigram("pec", "pec", "donna").
ham_trigram("the", "deal", "is").
ham_trigram("from", "george", "weissman").
ham_trigram("there", "are", "any").
ham_trigram("05", "01", "ena").
ham_trigram("following", "counterparty", "meter").
ham_trigram("contract", "thanks", "vlt").
ham_trigram("ect", "george", "weissman").
ham_trigram("susan", "d", "trevino").
ham_trigram("fax", "calpine", "daily").
ham_trigram("d", "original", "message").
ham_trigram("nomination", "change", "effective").
ham_trigram("45", "pm", "to").
ham_trigram("re", "noms", "actual").
ham_trigram("to", "farmer", "daren").
ham_trigram("the", "above", "meter").
ham_trigram("be", "allocated", "to").
ham_trigram("d", "forwarded", "by").
ham_trigram("the", "following", "production").
ham_trigram("for", "the", "remaining").
ham_trigram("neal", "d", "winfree").
ham_trigram("farmer", "enron", "com").
ham_trigram("at", "this", "time").
ham_trigram("by", "robert", "e").
ham_trigram("tess", "ray", "enron").
ham_trigram("let", "us", "know").
ham_trigram("that", "this", "is").
ham_trigram("ect", "ect", "edward").
ham_trigram("by", "gary", "a").
ham_trigram("this", "meter", "for").
ham_trigram("of", "the", "gas").
ham_trigram("you", "will", "need").
ham_trigram("briley", "enron", "com").
ham_trigram("enron", "on", "02").
ham_trigram("royal", "_", "b").
ham_trigram("_", "b", "_").
ham_trigram("b", "_", "edmondson").
ham_trigram("_", "edmondson", "reliantenergy").
ham_trigram("edmondson", "reliantenergy", "com").
ham_trigram("copy", "of", "the").
ham_trigram("steve", "holmes", "on").
ham_trigram("00", "production", "encina").
ham_trigram("production", "encina", "gas").
ham_trigram("encina", "gas", "marketing").
ham_trigram("1", "16", "99").
ham_trigram("forwarded", "by", "melissa").
ham_trigram("120", "000", "hpl").
ham_trigram("counterparty", "meter", "volumes").
ham_trigram("ect", "james", "mckay").
ham_trigram("ect", "robert", "cotten").
ham_trigram("pm", "to", "gary").
ham_trigram("counterparty", "meter", "volume").
ham_trigram("hillary", "mack", "corp").
ham_trigram("mack", "corp", "enron").
ham_trigram("you", "for", "your").
ham_trigram("of", "the", "contract").
ham_trigram("ect", "enron", "com").
ham_trigram("the", "texas", "desk").
ham_trigram("me", "know", "when").
ham_trigram("that", "we", "can").
ham_trigram("pm", "to", "cc").
ham_trigram("xls", "subject", "hpl").
ham_trigram("will", "be", "able").
ham_trigram("duke", "energy", "trading").
ham_trigram("000", "enron", "ls").
ham_trigram("you", "need", "to").
ham_trigram("you", "do", "not").
ham_trigram("jill", "t", "zivley").
ham_trigram("walker", "hou", "ect").
ham_trigram("teco", "tap", "40").
ham_trigram("tap", "40", "000").
ham_trigram("what", "you", "think").
ham_trigram("from", "megan", "parker").
ham_trigram("steve", "venturatos", "hou").
ham_trigram("venturatos", "hou", "ect").
ham_trigram("enron", "actuals", "for").
ham_trigram("100", "gas", "daily").
ham_trigram("click", "on", "the").
ham_trigram("be", "set", "up").
ham_trigram("subject", "hpl", "noms").
ham_trigram("cc", "howard", "b").
ham_trigram("the", "above", "referenced").
ham_trigram("want", "me", "to").
ham_trigram("3", "9497", "subject").
ham_trigram("re", "meter", "1266").
ham_trigram("corp", "from", "gary").
ham_trigram("ect", "ect", "john").
ham_trigram("if", "you", "would").
ham_trigram("to", "dfarmer", "enron").
ham_trigram("michael", "r", "cherry").
ham_trigram("w", "cass", "gcs").
ham_trigram("cass", "gcs", "cec").
ham_trigram("ect", "ect", "brenda").
ham_trigram("gas", "daily", "subject").
ham_trigram("following", "information", "counterparty").
ham_trigram("robert", "superty", "hou").
ham_trigram("superty", "hou", "ect").
ham_trigram("9", "6", "00").
ham_trigram("janet", "h", "wallis").
ham_trigram("for", "10", "00").
ham_trigram("deals", "in", "sitara").
ham_trigram("to", "change", "the").
ham_trigram("has", "been", "created").
ham_trigram("ticket", "for", "the").
ham_trigram("schneider", "hou", "ect").
ham_trigram("t", "zivley", "hou").
ham_trigram("zivley", "hou", "ect").
ham_trigram("d", "winfree", "hou").
ham_trigram("winfree", "hou", "ect").
ham_trigram("robert", "walker", "hou").
ham_trigram("i", "will", "need").
ham_trigram("is", "not", "a").
ham_trigram("27", "am", "to").
ham_trigram("if", "you", "can").
ham_trigram("_", "a", "_").
ham_trigram("heidi", "withers", "hou").
ham_trigram("the", "price", "for").
ham_trigram("9", "00", "am").
ham_trigram("nom", "for", "march").
ham_trigram("should", "have", "been").
ham_trigram("ect", "cc", "howard").
ham_trigram("pm", "to", "jackie").
ham_trigram("be", "out", "of").
ham_trigram("to", "do", "this").
ham_trigram("daren", "can", "you").
ham_trigram("corp", "from", "robert").
ham_trigram("from", "robert", "cotten").
ham_trigram("d", "gottlob", "hou").
ham_trigram("gottlob", "hou", "ect").
ham_trigram("ect", "on", "10").
ham_trigram("e", "speckels", "gcs").
ham_trigram("speckels", "gcs", "cec").
ham_trigram("cherry", "easttexas", "pefs").
ham_trigram("information", "counterparty", "meter").
ham_trigram("the", "following", "natural").
ham_trigram("following", "natural", "gas").
ham_trigram("natural", "gas", "requirements").
ham_trigram("gas", "requirements", "for").
ham_trigram("each", "of", "you").
ham_trigram("fw", "march", "2001").
ham_trigram("sun", "11", "4").
ham_trigram("11", "4", "2001").
ham_trigram("4", "2001", "at").
ham_trigram("pm", "to", "david").
ham_trigram("re", "coastal", "oil").
ham_trigram("mark", "x", "33396").
ham_trigram("if", "you", "do").
ham_trigram("the", "demand", "fee").
ham_trigram("and", "a", "ticket").
ham_trigram("a", "ticket", "should").
ham_trigram("meter", "volumes", "price").
ham_trigram("mary", "jo", "johnson").
ham_trigram("bryan", "hou", "ect").
ham_trigram("ect", "brian", "m").
ham_trigram("addition", "to", "the").
ham_trigram("just", "wanted", "to").
ham_trigram("troy", "_", "a").
ham_trigram("a", "_", "benoit").
ham_trigram("_", "benoit", "reliantenergy").
ham_trigram("benoit", "reliantenergy", "com").
ham_trigram("d", "trevino", "hou").
ham_trigram("trevino", "hou", "ect").
ham_trigram("44", "pm", "to").
ham_trigram("withers", "hou", "ect").
ham_trigram("the", "rest", "of").
ham_trigram("in", "the", "future").
ham_trigram("hpl", "noms", "for").
ham_trigram("that", "we", "have").
ham_trigram("villarreal", "hou", "ect").
ham_trigram("it", "will", "be").
ham_trigram("to", "pat", "clynes").
ham_trigram("38", "pm", "to").
ham_trigram("should", "you", "have").
ham_trigram("r", "cherry", "easttexas").
ham_trigram("there", "is", "no").
ham_trigram("michael", "eiben", "hou").
ham_trigram("eiben", "hou", "ect").
ham_trigram("call", "if", "you").
ham_trigram("10", "000", "enron").
ham_trigram("due", "to", "the").
ham_trigram("to", "get", "this").
ham_trigram("karen", "lindley", "corp").
ham_trigram("lindley", "corp", "enron").
ham_trigram("need", "to", "know").
ham_trigram("do", "you", "know").
ham_trigram("corp", "from", "george").
ham_trigram("enron", "net", "works").
ham_trigram("l", "taylor", "enron").
ham_trigram("to", "have", "the").
ham_trigram("the", "albrecht", "4").
ham_trigram("volumes", "price", "period").
ham_trigram("the", "remaining", "term").
ham_trigram("remaining", "term", "of").
ham_trigram("steve", "hpl", "schneider").
ham_trigram("ect", "ect", "brian").
ham_trigram("forwarded", "by", "mary").
ham_trigram("subject", "enron", "actuals").
ham_trigram("subject", "fw", "fw").
ham_trigram("cc", "subject", "nom").
ham_trigram("set", "up", "a").
ham_trigram("texas", "general", "land").
ham_trigram("meter", "volume", "price").
ham_trigram("for", "the", "gas").
ham_trigram("please", "give", "me").
ham_trigram("natural", "gas", "nomination").
ham_trigram("03", "03", "2000").
ham_trigram("14", "pm", "to").
ham_trigram("questions", "or", "concerns").
ham_trigram("11", "01", "2000").
ham_trigram("taylor", "enron", "enronxgate").
ham_trigram("crow", "o", "connor").
ham_trigram("by", "the", "end").
ham_trigram("at", "the", "time").
ham_trigram("actuals", "for", "august").
ham_trigram("production", "is", "now").
ham_trigram("committed", "reserves", "firm").
ham_trigram("enron", "enron", "robert").
ham_trigram("desk", "to", "desk").
ham_trigram("pm", "to", "lee").
ham_trigram("forwarded", "by", "beverly").
ham_trigram("by", "beverly", "beaty").
ham_trigram("we", "will", "have").
ham_trigram("you", "are", "not").
ham_trigram("may", "not", "be").
ham_trigram("00", "am", "to").
ham_trigram("forwarded", "by", "jackie").
ham_trigram("by", "jackie", "young").
ham_trigram("500", "mmbtu", "d").
ham_trigram("subject", "hpl", "meter").
ham_trigram("01", "we", "agree").
ham_trigram("ponton", "on", "03").
ham_trigram("you", "want", "me").
ham_trigram("50", "pm", "to").
ham_trigram("kimberly", "vaughn", "hou").
ham_trigram("vaughn", "hou", "ect").
ham_trigram("you", "would", "like").
ham_trigram("here", "are", "the").
ham_trigram("pefs", "pec", "on").
ham_trigram("know", "if", "there").
ham_trigram("actuals", "for", "july").
ham_trigram("know", "if", "this").
ham_trigram("with", "any", "questions").
ham_trigram("com", "subject", "re").
ham_trigram("i", "wanted", "to").
ham_trigram("2001", "teco", "tap").
ham_trigram("lsk", "ic", "20").
ham_trigram("ic", "20", "000").
ham_trigram("following", "production", "is").
ham_trigram("is", "now", "on").
ham_trigram("now", "on", "line").
ham_trigram("mmbtu", "d", "85").
ham_trigram("deal", "and", "should").
ham_trigram("hpl", "schneider", "hou").
ham_trigram("ect", "ect", "earl").
ham_trigram("ect", "earl", "tisdale").
ham_trigram("na", "enron", "on").
ham_trigram("to", "gary", "w").
ham_trigram("the", "attached", "file").
ham_trigram("the", "transaction", "agreement").
ham_trigram("am", "enron", "capital").
ham_trigram("the", "intended", "recipient").
ham_trigram("will", "be", "the").
ham_trigram("we", "will", "need").
ham_trigram("a", "chance", "to").
ham_trigram("42", "am", "to").
ham_trigram("basin", "production", "from").
ham_trigram("production", "from", "ga").
ham_trigram("from", "ga", "213").
ham_trigram("forwarded", "by", "brenda").
ham_trigram("by", "brenda", "f").
ham_trigram("to", "pg", "e").
ham_trigram("don", "t", "think").
ham_trigram("you", "have", "a").
ham_trigram("ect", "brenda", "f").
ham_trigram("is", "on", "the").
ham_trigram("to", "be", "effective").
ham_trigram("d", "85", "if").
ham_trigram("the", "mtbe", "plant").
ham_trigram("11", "21", "2000").
ham_trigram("has", "not", "been").
ham_trigram("it", "would", "be").
ham_trigram("what", "is", "the").
ham_trigram("flynn", "hou", "ect").
ham_trigram("cal", "ect", "ect").
ham_trigram("to", "tom", "acton").
ham_trigram("you", "have", "questions").
ham_trigram("flow", "for", "03").
ham_trigram("bob", "vance", "l").
ham_trigram("cc", "julie", "meyers").
ham_trigram("subject", "first", "delivery").
ham_trigram("bob", "the", "following").
ham_trigram("beginning", "with", "the").
ham_trigram("donna", "consemiu", "hou").
ham_trigram("consemiu", "hou", "ect").
ham_trigram("ect", "david", "baumbach").
ham_trigram("your", "e", "mail").
ham_trigram("will", "be", "available").
ham_trigram("will", "let", "you").
ham_trigram("sheri", "thomas", "hou").
ham_trigram("thomas", "hou", "ect").
ham_trigram("enron", "on", "01").
ham_trigram("mmbtu", "d", "into").
ham_trigram("know", "what", "the").
ham_trigram("for", "the", "following").
ham_trigram("to", "ray", "tess").
ham_trigram("it", "should", "be").
ham_trigram("questions", "please", "let").
ham_trigram("please", "change", "the").
ham_trigram("com", "on", "02").
ham_trigram("for", "gas", "loss").
ham_trigram("e", "lloyd", "08").
ham_trigram("enron", "enron", "rita").
ham_trigram("enron", "rita", "wynne").
ham_trigram("ect", "ect", "tom").
ham_trigram("cc", "robert", "e").
ham_trigram("pec", "pec", "cc").
ham_trigram("c", "spencer", "gcs").
ham_trigram("spencer", "gcs", "cec").
ham_trigram("an", "accounting", "arrangement").
ham_trigram("subject", "nom", "change").
ham_trigram("duke", "energy", "field").
ham_trigram("pec", "pec", "william").
ham_trigram("pec", "william", "e").
ham_trigram("call", "me", "if").
ham_trigram("40", "enron", "enron").
ham_trigram("enron", "enron", "com").
ham_trigram("re", "meter", "0986725").
ham_trigram("i", "have", "not").
ham_trigram("it", "is", "my").
ham_trigram("is", "a", "producer").
ham_trigram("producer", "svcs", "deal").
ham_trigram("svcs", "deal", "and").
ham_trigram("jo", "johnson", "hou").
ham_trigram("sweeney", "hou", "ect").
ham_trigram("enronxgate", "on", "04").
ham_trigram("first", "of", "the").
ham_trigram("for", "you", "to").
ham_trigram("less", "0", "10").
ham_trigram("deals", "and", "should").
ham_trigram("at", "http", "www").
ham_trigram("at", "the", "end").
ham_trigram("to", "be", "a").
ham_trigram("will", "be", "purchased").
ham_trigram("strangers", "gas", "contract").
ham_trigram("17", "am", "to").
ham_trigram("i", "ll", "be").
ham_trigram("is", "going", "to").
ham_trigram("thank", "you", "mary").
ham_trigram("that", "we", "are").
ham_trigram("a", "demand", "fee").
ham_trigram("production", "will", "be").
ham_trigram("look", "forward", "to").
ham_trigram("ect", "ect", "katherine").
ham_trigram("the", "deal", "ticket").
ham_trigram("mmbtu", "dy", "the").
ham_trigram("joanie", "h", "ngo").
ham_trigram("teco", "tap", "10").
ham_trigram("to", "write", "off").
ham_trigram("aimee", "forwarded", "by").
ham_trigram("need", "to", "do").
ham_trigram("if", "it", "is").
ham_trigram("on", "03", "21").
ham_trigram("pec", "pec", "john").
ham_trigram("john", "a", "bretz").
ham_trigram("need", "to", "have").
ham_trigram("this", "is", "not").
ham_trigram("25", "pm", "to").
ham_trigram("_", "development", "enron").
ham_trigram("development", "enron", "_").
ham_trigram("tina", "valadez", "hou").
ham_trigram("valadez", "hou", "ect").
ham_trigram("0", "1012", "6934").
ham_trigram("1012", "6934", "0").
ham_trigram("07", "10", "2000").
ham_trigram("from", "vance", "l").
ham_trigram("to", "have", "a").
ham_trigram("on", "line", "and").
ham_trigram("with", "the", "month").
ham_trigram("ect", "stephanie", "gomes").
ham_trigram("christy", "sweeney", "hou").
ham_trigram("53", "pm", "to").
ham_trigram("take", "a", "look").
ham_trigram("ami", "chokshi", "enron").
ham_trigram("ls", "hpl", "katy").
ham_trigram("53", "am", "to").
ham_trigram("for", "the", "first").
ham_trigram("in", "sitara", "for").
ham_trigram("24", "pm", "to").
ham_trigram("d", "100", "gas").
ham_trigram("58", "am", "to").
ham_trigram("10", "000", "d").
ham_trigram("cc", "subject", "revised").
ham_trigram("please", "make", "sure").
ham_trigram("to", "vance", "l").
ham_trigram("this", "production", "will").
ham_trigram("ect", "ect", "jennifer").
ham_trigram("ect", "ect", "kristen").
ham_trigram("ect", "kristen", "j").
ham_trigram("donna", "c", "spencer").
ham_trigram("pec", "pec", "chad").
ham_trigram("pec", "chad", "w").
ham_trigram("darrel", "f", "bane").
ham_trigram("f", "bane", "easttexas").
ham_trigram("bane", "easttexas", "pefs").
ham_trigram("nomination", "ricky", "a").
ham_trigram("tap", "10", "000").
ham_trigram("11", "pm", "to").
ham_trigram("we", "do", "not").
ham_trigram("thanks", "clem", "subject").
ham_trigram("listed", "below", "for").
ham_trigram("mary", "poorman", "enron").
ham_trigram("this", "is", "to").
ham_trigram("gas", "nomination", "for").
ham_trigram("the", "methanol", "plant").
ham_trigram("to", "fred", "boas").
ham_trigram("a", "deal", "for").
ham_trigram("a", "bretz", "gcs").
ham_trigram("bretz", "gcs", "cec").
ham_trigram("pec", "pec", "julia").
ham_trigram("pec", "julia", "a").
ham_trigram("julia", "a", "urbanek").
ham_trigram("bob", "m", "hall").
ham_trigram("mary", "solmonson", "hou").
ham_trigram("solmonson", "hou", "ect").
ham_trigram("for", "9", "6").
ham_trigram("continue", "to", "be").

% Kiểm tra email có phải spam hay ham
classify_email(Text, Result, SpamPercent, HamPercent) :-
    split_string(Text, " ", "", Words),
    findall((W1, W2, W3), (nth0(I, Words, W1), nth0(J, Words, W2), nth0(K, Words, W3), J is I + 1, K is J + 1, spam_trigram(W1, W2, W3)), SpamTrigrams),
    findall((W1, W2, W3), (nth0(I, Words, W1), nth0(J, Words, W2), nth0(K, Words, W3), J is I + 1, K is J + 1, ham_trigram(W1, W2, W3)), HamTrigrams),
    length(SpamTrigrams, SpamCount),
    length(HamTrigrams, HamCount),
    Total is SpamCount + HamCount,
    (Total > 0 ->
            SpamPercent is (SpamCount / Total) * 100,
            HamPercent is (HamCount / Total) * 100;
            SpamPercent = 0.0,
            HamPercent = 0.0
    ),
    (SpamCount > HamCount -> Result = "spam"; Result = "ham").