% Top spam bigrams
spam_bigram("of", "the").
spam_bigram("in", "the").
spam_bigram("if", "you").
spam_bigram("http", "www").
spam_bigram("_", "_").
spam_bigram("the", "company").
spam_bigram("to", "be").
spam_bigram("of", "this").
spam_bigram("nbsp", "nbsp").
spam_bigram("with", "the").
spam_bigram("on", "the").
spam_bigram("to", "the").
spam_bigram("for", "the").
spam_bigram("is", "a").
spam_bigram("you", "can").
spam_bigram("you", "have").
spam_bigram("3", "d").
spam_bigram("this", "report").
spam_bigram("this", "is").
spam_bigram("computron", "me").
spam_bigram("me", "com").
spam_bigram("in", "this").
spam_bigram("within", "this").
spam_bigram("href", "http").
spam_bigram("looking", "statements").
spam_bigram("of", "your").
spam_bigram("this", "email").
spam_bigram("this", "message").
spam_bigram("will", "be").
spam_bigram("is", "not").
spam_bigram("don", "t").
spam_bigram("src", "http").
spam_bigram("and", "the").
spam_bigram("not", "be").
spam_bigram("border", "0").
spam_bigram("www", "computron").
spam_bigram("up", "to").
spam_bigram("click", "here").
spam_bigram("it", "is").
spam_bigram("to", "you").
spam_bigram("a", "href").
spam_bigram("we", "are").
spam_bigram("forward", "looking").
spam_bigram("at", "the").
spam_bigram("u", "s").
spam_bigram("is", "the").
spam_bigram("http", "69").
spam_bigram("69", "63").
spam_bigram("63", "161").
spam_bigram("you", "are").
spam_bigram("_", "nd").
spam_bigram("nd", "_").
spam_bigram("for", "a").
spam_bigram("td", "td").
spam_bigram("e", "mail").
spam_bigram("from", "the").
spam_bigram("company", "s").
spam_bigram("by", "the").
spam_bigram("for", "you").
spam_bigram("act", "of").
spam_bigram("have", "been").
spam_bigram("may", "be").
spam_bigram("investment", "advice").
spam_bigram("we", "have").
spam_bigram("color", "3").
spam_bigram("based", "on").
spam_bigram("font", "size").
spam_bigram("you", "will").
spam_bigram("of", "these").
spam_bigram("td", "tr").
spam_bigram("the", "securities").
spam_bigram("with", "a").
spam_bigram("to", "this").
spam_bigram("i", "am").
spam_bigram("it", "s").
spam_bigram("in", "a").
spam_bigram("message", "is").
spam_bigram("of", "a").
spam_bigram("the", "best").
spam_bigram("for", "your").
spam_bigram("to", "get").
spam_bigram("of", "our").
spam_bigram("want", "to").
spam_bigram("to", "your").
spam_bigram("in", "your").
spam_bigram("from", "a").
spam_bigram("this", "newsletter").
spam_bigram("do", "not").
spam_bigram("that", "the").
spam_bigram("tr", "td").
spam_bigram("as", "a").
spam_bigram("subject", "re").
spam_bigram("161", "44").
spam_bigram("are", "the").
spam_bigram("align", "center").
spam_bigram("you", "to").
spam_bigram("reply", "to").
spam_bigram("is", "an").
spam_bigram("as", "the").
spam_bigram("can", "be").
spam_bigram("face", "3").
spam_bigram("does", "not").
spam_bigram("there", "is").
spam_bigram("subject", "to").
spam_bigram("thank", "you").
spam_bigram("one", "of").
spam_bigram("to", "receive").
spam_bigram("windows", "xp").
spam_bigram("and", "a").
spam_bigram("duty", "free").
spam_bigram("com", "for").
spam_bigram("971", "4").
spam_bigram("here", "to").
spam_bigram("use", "of").
spam_bigram("has", "been").
spam_bigram("ali", "duty").
spam_bigram("font", "family").
spam_bigram("td", "width").
spam_bigram("the", "most").
spam_bigram("within", "the").
spam_bigram("are", "not").
spam_bigram("a", "registered").
spam_bigram("like", "to").
spam_bigram("into", "your").
spam_bigram("information", "provided").
spam_bigram("to", "a").
spam_bigram("be", "removed").
spam_bigram("in", "our").
spam_bigram("on", "this").
spam_bigram("the", "publisher").
spam_bigram("publisher", "of").
spam_bigram("and", "gas").
spam_bigram("this", "link").
spam_bigram("xp", "professional").
spam_bigram("i", "have").
spam_bigram("statements", "are").
spam_bigram("about", "the").
spam_bigram("all", "the").
spam_bigram("have", "a").
spam_bigram("soft", "tabs").
spam_bigram("how", "to").
spam_bigram("compliance", "with").
spam_bigram("the", "world").
spam_bigram("your", "account").
spam_bigram("size", "3").
spam_bigram("you", "want").
spam_bigram("0", "src").
spam_bigram("a", "td").
spam_bigram("www", "moopid").
spam_bigram("moopid", "com").
spam_bigram("com", "hotlist").
spam_bigram("to", "make").
spam_bigram("in", "compliance").
spam_bigram("the", "link").
spam_bigram("60", "pills").
spam_bigram("tr", "tr").
spam_bigram("pt", "font").
spam_bigram("copy", "and").
spam_bigram("7", "0").
spam_bigram("risks", "and").
spam_bigram("your", "browser").
spam_bigram("such", "as").
spam_bigram("meaning", "of").
spam_bigram("part", "of").
spam_bigram("that", "you").
spam_bigram("and", "uncertainties").
spam_bigram("com", "subject").
spam_bigram("of", "their").
spam_bigram("and", "paste").
spam_bigram("should", "be").
spam_bigram("your", "own").
spam_bigram("due", "to").
spam_bigram("wish", "to").
spam_bigram("the", "subject").
spam_bigram("for", "any").
spam_bigram("you", "in").
spam_bigram("adobe", "photoshop").
spam_bigram("mx", "2004").
spam_bigram("p", "align").
spam_bigram("jpg", "width").
spam_bigram("securities", "act").
spam_bigram("the", "time").
spam_bigram("number", "of").
spam_bigram("from", "those").
spam_bigram("not", "a").
spam_bigram("a", "new").
spam_bigram("style", "line").
spam_bigram("line", "height").
spam_bigram("height", "15").
spam_bigram("15", "pt").
spam_bigram("family", "knle").
spam_bigram("knle", "font").
spam_bigram("size", "9").
spam_bigram("9", "pt").
spam_bigram("your", "money").
spam_bigram("may", "not").
spam_bigram("best", "regards").
spam_bigram("the", "statements").
spam_bigram("and", "other").
spam_bigram("as", "we").
spam_bigram("sent", "to").
spam_bigram("you", "need").
spam_bigram("iit", "demokritos").
spam_bigram("the", "new").
spam_bigram("our", "price").
spam_bigram("is", "for").
spam_bigram("to", "stop").
spam_bigram("no", "thanks").
spam_bigram("message", "this").
spam_bigram("demokritos", "gr").
spam_bigram("many", "of").
spam_bigram("without", "notice").
spam_bigram("would", "like").
spam_bigram("need", "to").
spam_bigram("here", "http").
spam_bigram("align", "3").
spam_bigram("to", "differ").
spam_bigram("you", "don").
spam_bigram("through", "the").
spam_bigram("should", "not").
spam_bigram("money", "back").
spam_bigram("out", "of").
spam_bigram("the", "next").
spam_bigram("and", "i").
spam_bigram("90", "pills").
spam_bigram("the", "internet").
spam_bigram("the", "meaning").
spam_bigram("of", "1933").
spam_bigram("are", "based").
spam_bigram("third", "party").
spam_bigram("this", "stock").
spam_bigram("the", "information").
spam_bigram("investing", "in").
spam_bigram("the", "first").
spam_bigram("do", "you").
spam_bigram("and", "more").
spam_bigram("to", "investing").
spam_bigram("go", "here").
spam_bigram("to", "unsubscribe").
spam_bigram("current", "price").
spam_bigram("you", "wish").
spam_bigram("jebel", "ali").
spam_bigram("microsoft", "office").
spam_bigram("united", "states").
spam_bigram("of", "interest").
spam_bigram("that", "is").
spam_bigram("in", "error").
spam_bigram("office", "xp").
spam_bigram("d", "2").
spam_bigram("statements", "within").
spam_bigram("with", "no").
spam_bigram("any", "other").
spam_bigram("is", "being").
spam_bigram("unsubscribe", "from").
spam_bigram("get", "the").
spam_bigram("the", "same").
spam_bigram("no", "more").
spam_bigram("gif", "width").
spam_bigram("looking", "for").
spam_bigram("the", "stock").
spam_bigram("follow", "this").
spam_bigram("here", "for").
spam_bigram("you", "save").
spam_bigram("you", "for").
spam_bigram("what", "you").
spam_bigram("rnd", "_").
spam_bigram("font", "color").
spam_bigram("oil", "and").
spam_bigram("for", "more").
spam_bigram("have", "any").
spam_bigram("to", "change").
spam_bigram("mail", "with").
spam_bigram("paste", "the").
spam_bigram("i", "m").
spam_bigram("of", "an").
spam_bigram("a", "number").
spam_bigram("must", "be").
spam_bigram("send", "your").
spam_bigram("prices", "and").
spam_bigram("with", "your").
spam_bigram("it", "was").
spam_bigram("font", "face").
spam_bigram("3", "darial").
spam_bigram("height", "120").
spam_bigram("and", "should").
spam_bigram("company", "has").
spam_bigram("this", "mail").
spam_bigram("be", "considered").
spam_bigram("1", "a").
spam_bigram("a", "and").
spam_bigram("more", "than").
spam_bigram("get", "a").
spam_bigram("44", "0310041").
spam_bigram("0310041", "_").
spam_bigram("_", "cf").
spam_bigram("of", "1934").
spam_bigram("an", "inherent").
spam_bigram("conflict", "of").
spam_bigram("ooking", "statements").
spam_bigram("and", "lots").
spam_bigram("lots", "more").
spam_bigram("long", "as").
spam_bigram("click", "the").
spam_bigram("retail", "price").
spam_bigram("00", "90").
spam_bigram("on", "a").
spam_bigram("to", "our").
spam_bigram("2", "oo").
spam_bigram("to", "do").
spam_bigram("as", "long").
spam_bigram("this", "list").
spam_bigram("the", "federal").
spam_bigram("and", "your").
spam_bigram("30", "pills").
spam_bigram("index", "htmlimg").
spam_bigram("161", "45").
spam_bigram("and", "may").
spam_bigram("the", "material").
spam_bigram("aware", "of").
spam_bigram("companies", "are").
spam_bigram("past", "performance").
spam_bigram("and", "we").
spam_bigram("as", "well").
spam_bigram("u", "a").
spam_bigram("receive", "our").
spam_bigram("special", "offers").
spam_bigram("error", "or").
spam_bigram("for", "commercial").
spam_bigram("99", "our").
spam_bigram("1", "cd").
spam_bigram("height", "124").
spam_bigram("45", "0424040").
spam_bigram("0424040", "_").
spam_bigram("_", "ftar").
spam_bigram("able", "to").
spam_bigram("to", "seek").
spam_bigram("you", "may").
spam_bigram("or", "for").
spam_bigram("line", "of").
spam_bigram("their", "respective").
spam_bigram("the", "address").
spam_bigram("will", "not").
spam_bigram("of", "us").
spam_bigram("the", "only").
spam_bigram("could", "cause").
spam_bigram("the", "use").
spam_bigram("inherent", "conflict").
spam_bigram("of", "all").
spam_bigram("contact", "our").
spam_bigram("for", "further").
spam_bigram("please", "send").
spam_bigram("s", "dollars").
spam_bigram("contact", "information").
spam_bigram("please", "reply").
spam_bigram("your", "message").
spam_bigram("and", "is").
spam_bigram("your", "email").
spam_bigram("photoshop", "7").
spam_bigram("email", "address").
spam_bigram("cs", "2").
spam_bigram("bgcolor", "000000").
spam_bigram("differ", "materially").
spam_bigram("materially", "from").
spam_bigram("some", "of").
spam_bigram("these", "companies").
spam_bigram("that", "this").
spam_bigram("has", "a").
spam_bigram("from", "our").
spam_bigram("prices", "in").
spam_bigram("our", "special").
spam_bigram("plain", "text").
spam_bigram("text", "format").
spam_bigram("only", "this").
spam_bigram("information", "remove").
spam_bigram("only", "if").
spam_bigram("being", "sent").
spam_bigram("logos", "and").
spam_bigram("the", "property").
spam_bigram("above", "to").
spam_bigram("to", "take").
spam_bigram("get", "it").
spam_bigram("get", "your").
spam_bigram("visit", "us").
spam_bigram("hotlist", "images").
spam_bigram("and", "not").
spam_bigram("material", "within").
spam_bigram("of", "investment").
spam_bigram("today", "s").
spam_bigram("yahoo", "com").
spam_bigram("for", "all").
spam_bigram("your", "one").
spam_bigram("one", "stop").
spam_bigram("further", "details").
spam_bigram("usa", "canada").
spam_bigram("offers", "in").
spam_bigram("for", "export").
spam_bigram("export", "only").
spam_bigram("is", "intended").
spam_bigram("list", "in").
spam_bigram("other", "reason").
spam_bigram("with", "remove").
spam_bigram("subject", "line").
spam_bigram("h", "r").
spam_bigram("s", "1618").
spam_bigram("all", "logos").
spam_bigram("and", "trademarks").
spam_bigram("trademarks", "are").
spam_bigram("property", "of").
spam_bigram("as", "shown").
spam_bigram("from", "computron").
spam_bigram("link", "or").
spam_bigram("microsoft", "windows").
spam_bigram("no", "prescription").
spam_bigram("have", "the").
spam_bigram("html", "subject").
spam_bigram("target", "price").
spam_bigram("on", "your").
spam_bigram("th", "_").
spam_bigram("of", "section").
spam_bigram("exchange", "act").
spam_bigram("any", "kind").
spam_bigram("kind", "of").
spam_bigram("under", "the").
spam_bigram("a", "third").
spam_bigram("of", "its").
spam_bigram("sales", "department").
spam_bigram("3", "com").
spam_bigram("com", "dell").
spam_bigram("more", "if").
spam_bigram("tel", "971").
spam_bigram("4", "8834464").
spam_bigram("8834464", "all").
spam_bigram("all", "prices").
spam_bigram("in", "u").
spam_bigram("dollars", "ex").
spam_bigram("ex", "works").
spam_bigram("fax", "971").
spam_bigram("4", "8834454").
spam_bigram("free", "zone").
spam_bigram("com", "prices").
spam_bigram("and", "availability").
spam_bigram("availability", "subject").
spam_bigram("canada", "u").
spam_bigram("a", "e").
spam_bigram("in", "plain").
spam_bigram("format", "reply").
spam_bigram("the", "request").
spam_bigram("request", "for").
spam_bigram("email", "can").
spam_bigram("can", "not").
spam_bigram("considered", "spam").
spam_bigram("spam", "as").
spam_bigram("we", "include").
spam_bigram("include", "contact").
spam_bigram("remove", "instructions").
spam_bigram("instructions", "this").
spam_bigram("intended", "for").
spam_bigram("for", "dealer").
spam_bigram("dealer", "and").
spam_bigram("and", "resellers").
spam_bigram("resellers", "only").
spam_bigram("have", "somehow").
spam_bigram("somehow", "gotten").
spam_bigram("gotten", "on").
spam_bigram("reason", "would").
spam_bigram("removed", "please").
spam_bigram("reply", "with").
spam_bigram("remove", "in").
spam_bigram("federal", "legislation").
spam_bigram("legislation", "for").
spam_bigram("commercial", "e").
spam_bigram("mail", "h").
spam_bigram("r", "4176").
spam_bigram("4176", "section").
spam_bigram("section", "101").
spam_bigram("101", "paragraph").
spam_bigram("paragraph", "e").
spam_bigram("e", "1").
spam_bigram("and", "bill").
spam_bigram("bill", "s").
spam_bigram("1618", "title").
spam_bigram("title", "iii").
spam_bigram("iii", "passed").
spam_bigram("passed", "by").
spam_bigram("the", "105").
spam_bigram("105", "th").
spam_bigram("th", "u").
spam_bigram("s", "congress").
spam_bigram("congress", "all").
spam_bigram("products", "may").
spam_bigram("be", "exactly").
spam_bigram("exactly", "as").
spam_bigram("shown", "above").
spam_bigram("just", "follow").
spam_bigram("link", "click").
spam_bigram("or", "copy").
spam_bigram("address", "into").
spam_bigram("at", "http").
spam_bigram("our", "site").
spam_bigram("to", "have").
spam_bigram("i", "will").
spam_bigram("44", "1226030").
spam_bigram("1226030", "_").
spam_bigram("_", "cs").
spam_bigram("securities", "exchange").
spam_bigram("statements", "of").
spam_bigram("of", "risks").
spam_bigram("prior", "to").
spam_bigram("be", "aware").
spam_bigram("which", "is").
spam_bigram("for", "latest").
spam_bigram("latest", "clearance").
spam_bigram("clearance", "sale").
spam_bigram("sale", "listing").
spam_bigram("listing", "contact").
spam_bigram("our", "sales").
spam_bigram("com", "compaq").
spam_bigram("compaq", "hewlett").
spam_bigram("hewlett", "packard").
spam_bigram("packard", "3").
spam_bigram("dell", "intel").
spam_bigram("intel", "iomega").
spam_bigram("iomega", "epson").
spam_bigram("epson", "aopen").
spam_bigram("aopen", "creative").
spam_bigram("creative", "toshiba").
spam_bigram("toshiba", "apc").
spam_bigram("apc", "cisco").
spam_bigram("cisco", "us").
spam_bigram("us", "robotics").
spam_bigram("robotics", "microsoft").
spam_bigram("microsoft", "canon").
spam_bigram("canon", "intellinet").
spam_bigram("intellinet", "targus").
spam_bigram("targus", "viewsonic").
spam_bigram("viewsonic", "ibm").
spam_bigram("ibm", "sony").
spam_bigram("sony", "and").
spam_bigram("any", "complaints").
spam_bigram("complaints", "suggestions").
spam_bigram("suggestions", "contact").
spam_bigram("contact", "customerservice").
spam_bigram("customerservice", "computron").
spam_bigram("works", "fax").
spam_bigram("8834454", "jebel").
spam_bigram("zone", "www").
spam_bigram("change", "usa").
spam_bigram("e", "without").
spam_bigram("s", "a").
spam_bigram("that", "i").
spam_bigram("i", "was").
spam_bigram("size", "1").
spam_bigram("over", "the").
spam_bigram("provided", "and").
spam_bigram("not", "investment").
spam_bigram("be", "construed").
spam_bigram("construed", "as").
spam_bigram("not", "an").
spam_bigram("details", "please").
spam_bigram("your", "enquiries").
spam_bigram("enquiries", "to").
spam_bigram("contact", "via").
spam_bigram("via", "www").
spam_bigram("com", "tel").
spam_bigram("notice", "to").
spam_bigram("all", "your").
spam_bigram("we", "can").
spam_bigram("go", "to").
spam_bigram("000", "00").
spam_bigram("all", "of").
spam_bigram("br", "br").
spam_bigram("it", "has").
spam_bigram("a", "of").
spam_bigram("be", "understood").
spam_bigram("to", "trade").
spam_bigram("none", "of").
spam_bigram("the", "news").
spam_bigram("not", "to").
spam_bigram("watch", "this").
spam_bigram("in", "any").
spam_bigram("there", "are").
spam_bigram("products", "and").
spam_bigram("36", "hours").
spam_bigram("not", "reply").
spam_bigram("nbsp", "td").
spam_bigram("china", "itoy").
spam_bigram("information", "within").
spam_bigram("section", "27").
spam_bigram("1933", "and").
spam_bigram("and", "section").
spam_bigram("section", "21").
spam_bigram("respect", "to").
spam_bigram("pertaining", "to").
spam_bigram("advice", "from").
spam_bigram("as", "any").
spam_bigram("interest", "in").
spam_bigram("this", "one").
spam_bigram("free", "zonedubai").
spam_bigram("zonedubai", "uae").
spam_bigram("uae", "www").
spam_bigram("to", "dealers").
spam_bigram("dealers", "emirates").
spam_bigram("emirates", "net").
spam_bigram("net", "aeor").
spam_bigram("aeor", "contact").
spam_bigram("low", "price").
spam_bigram("visit", "http").
spam_bigram("world", "wide").
spam_bigram("php", "subject").
spam_bigram("you", "would").
spam_bigram("27", "a").
spam_bigram("time", "the").
spam_bigram("are", "made").
spam_bigram("statements", "in").
spam_bigram("provided", "within").
spam_bigram("securities", "must").
spam_bigram("understood", "as").
spam_bigram("as", "information").
spam_bigram("seek", "advice").
spam_bigram("securities", "representative").
spam_bigram("representative", "before").
spam_bigram("before", "deciding").
spam_bigram("deciding", "to").
spam_bigram("trade", "in").
spam_bigram("featured", "within").
spam_bigram("from", "such").
spam_bigram("investment", "advisor").
spam_bigram("that", "it").
spam_bigram("future", "looking").
spam_bigram("send", "a").
spam_bigram("we", "will").
spam_bigram("corel", "draw").
spam_bigram("for", "deals").
spam_bigram("the", "money").
spam_bigram("be", "a").
spam_bigram("are", "you").
spam_bigram("they", "are").
spam_bigram("that", "will").
spam_bigram("p", "p").
spam_bigram("69", "95").
spam_bigram("windows", "2000").
spam_bigram("32", "00").
spam_bigram("_", "alt").
spam_bigram("valign", "middle").
spam_bigram("itoy", "com").
spam_bigram("statements", "that").
spam_bigram("with", "respect").
spam_bigram("made", "that").
spam_bigram("be", "identified").
spam_bigram("investing", "stocks").
spam_bigram("in", "stocks").
spam_bigram("stocks", "featured").
spam_bigram("at", "any").
spam_bigram("no", "assurance").
spam_bigram("stop", "future").
spam_bigram("is", "to").
spam_bigram("or", "a").
spam_bigram("the", "market").
spam_bigram("respective", "owners").
spam_bigram("e", "r").
spam_bigram("s", "health").
spam_bigram("a", "few").
spam_bigram("sources", "said").
spam_bigram("000", "000").
spam_bigram("font", "p").
spam_bigram("mg", "30").
spam_bigram("00", "60").
spam_bigram("div", "align").
spam_bigram("124", "a").
spam_bigram("weight", "loss").
spam_bigram("to", "help").
spam_bigram("21", "b").
spam_bigram("expectations", "estimates").
spam_bigram("estimates", "and").
spam_bigram("and", "projections").
spam_bigram("projections", "at").
spam_bigram("uncertainties", "which").
spam_bigram("actual", "results").
spam_bigram("events", "to").
spam_bigram("of", "words").
spam_bigram("words", "such").
spam_bigram("that", "by").
spam_bigram("stocks", "securities").
spam_bigram("can", "make").
spam_bigram("to", "see").
spam_bigram("the", "results").
spam_bigram("me", "to").
spam_bigram("that", "we").
spam_bigram("we", "offer").
spam_bigram("to", "use").
spam_bigram("you", "ve").
spam_bigram("can", "get").
spam_bigram("img", "border").
spam_bigram("width", "124").
spam_bigram("www", "china").
spam_bigram("ability", "to").
spam_bigram("1934", "any").
spam_bigram("any", "statements").
spam_bigram("discussions", "with").
spam_bigram("to", "predictions").
spam_bigram("projections", "objectives").
spam_bigram("assumptions", "or").
spam_bigram("future", "events").
spam_bigram("or", "performance").
spam_bigram("performance", "are").
spam_bigram("not", "statements").
spam_bigram("fact", "and").
spam_bigram("on", "expectations").
spam_bigram("or", "events").
spam_bigram("this", "action").
spam_bigram("action", "may").
spam_bigram("identified", "through").
spam_bigram("as", "projects").
spam_bigram("projects", "foresee").
spam_bigram("foresee", "expects").
spam_bigram("or", "that").
spam_bigram("readers", "and").
spam_bigram("and", "subscribers").
spam_bigram("subscribers", "to").
spam_bigram("not", "represent").
spam_bigram("any", "time").
spam_bigram("registered", "investment").
spam_bigram("contained", "in").
spam_bigram("of", "future").
spam_bigram("a", "review").
spam_bigram("or", "if").
spam_bigram("oi", "and").
spam_bigram("less", "than").
spam_bigram("the", "past").
spam_bigram("more", "info").
spam_bigram("in", "order").
spam_bigram("order", "to").
spam_bigram("r", "a").
spam_bigram("owners", "products").
spam_bigram("read", "the").
spam_bigram("paliourg", "iit").
spam_bigram("you", "get").
spam_bigram("content", "type").
spam_bigram("please", "do").
spam_bigram("i", "ve").
spam_bigram("font", "strong").
spam_bigram("valign", "top").
spam_bigram("be", "able").
spam_bigram("b", "of").
spam_bigram("by", "statements").
spam_bigram("statements", "indicating").
spam_bigram("indicating", "certain").
spam_bigram("certain", "actions").
spam_bigram("actions", "may").
spam_bigram("or", "might").
spam_bigram("might", "occur").
spam_bigram("to", "say").
spam_bigram("which", "are").
spam_bigram("due", "diligence").
spam_bigram("after", "the").
spam_bigram("the", "price").
spam_bigram("was", "a").
spam_bigram("subject", "get").
spam_bigram("pain", "relief").
spam_bigram("company", "is").
spam_bigram("way", "to").
spam_bigram("for", "me").
spam_bigram("i", "a").
spam_bigram("we", "believe").
spam_bigram("it", "to").
spam_bigram("and", "you").
spam_bigram("we", "ship").
spam_bigram("you", "do").
spam_bigram("00", "32").
spam_bigram("darial", "color").
spam_bigram("td", "height").
spam_bigram("style", "font").
spam_bigram("a", "company").
spam_bigram("cause", "actual").
spam_bigram("and", "in").
spam_bigram("report", "be").
spam_bigram("interest", "resulting").
spam_bigram("resulting", "from").
spam_bigram("this", "publication").
spam_bigram("the", "pubiisher").
spam_bigram("to", "its").
spam_bigram("to", "buy").
spam_bigram("index", "php").
spam_bigram("you", "could").
spam_bigram("please", "click").
spam_bigram("it", "will").
spam_bigram("check", "out").
spam_bigram("you", "the").
spam_bigram("xp", "pro").
spam_bigram("htmlimg", "border").
spam_bigram("center", "width").
spam_bigram("plans", "projections").
spam_bigram("registered", "professional").
spam_bigram("professional", "securities").
spam_bigram("easy", "to").
spam_bigram("this", "information").
spam_bigram("with", "this").
spam_bigram("forward", "ooking").
spam_bigram("in", "my").
spam_bigram("at", "a").
spam_bigram("i", "can").
spam_bigram("v", "i").
spam_bigram("help", "you").
spam_bigram("prescription", "required").
spam_bigram("thanks", "http").
spam_bigram("00", "20").
spam_bigram("here", "subject").
spam_bigram("face", "verdana").
spam_bigram("verdana", "size").
spam_bigram("124", "height").
spam_bigram("tr", "table").
spam_bigram("hotlist", "hottlist").
spam_bigram("hottlist", "_").
spam_bigram("_", "09").
spam_bigram("high", "quality").
spam_bigram("is", "no").
spam_bigram("agreement", "with").
spam_bigram("or", "involve").
spam_bigram("expectations", "beliefs").
spam_bigram("events", "or").
spam_bigram("those", "presently").
spam_bigram("presently", "anticipated").
spam_bigram("and", "are").
spam_bigram("necessary", "to").
spam_bigram("of", "that").
spam_bigram("as", "to").
spam_bigram("of", "you").
spam_bigram("instant", "download").
spam_bigram("subject", "the").
spam_bigram("and", "it").
spam_bigram("is", "your").
spam_bigram("to", "go").
spam_bigram("and", "many").
spam_bigram("many", "more").
spam_bigram("this", "letter").
spam_bigram("with", "our").
spam_bigram("price", "of").
spam_bigram("international", "inc").
spam_bigram("have", "to").
spam_bigram("99", "90").
spam_bigram("pills", "149").
spam_bigram("price", "69").
spam_bigram("25", "00").
spam_bigram("td", "bgcolor").
spam_bigram("000000", "align").
spam_bigram("full", "story").
spam_bigram("price", "0").
spam_bigram("contains", "forward").
spam_bigram("that", "express").
spam_bigram("express", "or").
spam_bigram("or", "future").
spam_bigram("that", "involve").
spam_bigram("also", "have").
spam_bigram("performance", "is").
spam_bigram("information", "in").
spam_bigram("press", "releases").
spam_bigram("the", "following").
spam_bigram("featured", "company").
spam_bigram("our", "low").
spam_bigram("graphics", "suite").
spam_bigram("the", "u").
spam_bigram("deals", "your").
spam_bigram("can", "t").
spam_bigram("make", "a").
spam_bigram("is", "here").
spam_bigram("into", "the").
spam_bigram("flash", "mx").
spam_bigram("take", "a").
spam_bigram("cialis", "soft").
spam_bigram("120", "pills").
spam_bigram("00", "25").
spam_bigram("20", "00").
spam_bigram("this", "money").
spam_bigram("when", "i").
spam_bigram("in", "their").
spam_bigram("width", "120").
spam_bigram("access", "to").
spam_bigram("involve", "discussions").
spam_bigram("beliefs", "plans").
spam_bigram("results", "or").
spam_bigram("estimates", "believes").
spam_bigram("believes", "understands").
spam_bigram("may", "could").
spam_bigram("could", "or").
spam_bigram("news", "release").
spam_bigram("of", "any").
spam_bigram("make", "the").
spam_bigram("report", "is").
spam_bigram("accuracy", "or").
spam_bigram("acceptance", "of").
spam_bigram("here", "or").
spam_bigram("and", "to").
spam_bigram("half", "a").
spam_bigram("companies", "that").
spam_bigram("come", "to").
spam_bigram("to", "80").
spam_bigram("and", "that").
spam_bigram("a", "pill").
spam_bigram("of", "my").
spam_bigram("to", "avoid").
spam_bigram("contents", "of").
spam_bigram("a", "month").
spam_bigram("for", "free").
spam_bigram("find", "out").
spam_bigram("0", "60").
spam_bigram("more", "information").
spam_bigram("did", "not").
spam_bigram("want", "a").
spam_bigram("as", "an").
spam_bigram("well", "as").
spam_bigram("to", "confirm").
spam_bigram("your", "claims").
spam_bigram("td", "colspan").
spam_bigram("january", "2004").
spam_bigram("2004", "full").
spam_bigram("expected", "to").
spam_bigram("inc", "is").
spam_bigram("into", "a").
spam_bigram("be", "forward").
spam_bigram("the", "above").
spam_bigram("newsletter", "is").
spam_bigram("to", "continue").
spam_bigram("information", "contained").
spam_bigram("advice", "or").
spam_bigram("but", "not").
spam_bigram("the", "fact").
spam_bigram("fact", "that").
spam_bigram("stop", "distributorjebel").
spam_bigram("distributorjebel", "ali").
spam_bigram("a", "very").
spam_bigram("future", "mailings").
spam_bigram("is", "now").
spam_bigram("all", "natural").
spam_bigram("your", "door").
spam_bigram("this", "transaction").
spam_bigram("0", "a").
spam_bigram("you", "and").
spam_bigram("is", "that").
spam_bigram("be", "the").
spam_bigram("doesn", "t").
spam_bigram("2", "3").
spam_bigram("won", "t").
spam_bigram("we", "ll").
spam_bigram("save", "up").
spam_bigram("img", "src").
spam_bigram("your", "life").
spam_bigram("that", "your").
spam_bigram("font", "font").
spam_bigram("120", "height").
spam_bigram("120", "a").
spam_bigram("2", "face").
spam_bigram("going", "to").
spam_bigram("in", "next").
spam_bigram("statements", "forward").
spam_bigram("which", "could").
spam_bigram("anticipated", "forward").
spam_bigram("shall", "be").
spam_bigram("reliance", "on").
spam_bigram("or", "sell").
spam_bigram("term", "target").
spam_bigram("and", "services").
spam_bigram("a", "going").
spam_bigram("going", "concern").
spam_bigram("or", "solicitation").
spam_bigram("pubiisher", "of").
spam_bigram("be", "no").
spam_bigram("indicative", "of").
spam_bigram("receipt", "of").
spam_bigram("a", "paid").
spam_bigram("department", "for").
spam_bigram("r", "e").
spam_bigram("special", "offer").
spam_bigram("information", "on").
spam_bigram("thousands", "of").
spam_bigram("and", "or").
spam_bigram("men", "s").
spam_bigram("let", "me").
spam_bigram("the", "contents").
spam_bigram("g", "r").
spam_bigram("world", "trade").
spam_bigram("a", "free").
spam_bigram("you", "ll").
spam_bigram("can", "do").
spam_bigram("below", "and").
spam_bigram("fill", "out").
spam_bigram("it", "out").
spam_bigram("from", "this").
spam_bigram("shares", "of").
spam_bigram("voice", "over").
spam_bigram("of", "historical").
spam_bigram("historical", "fact").
spam_bigram("involve", "a").
spam_bigram("all", "readers").
spam_bigram("that", "could").
spam_bigram("position", "in").
spam_bigram("long", "term").
spam_bigram("other", "factors").
spam_bigram("risk", "factors").
spam_bigram("continue", "as").
spam_bigram("are", "on").

% Top ham bigrams
ham_bigram("hou", "ect").
ham_bigram("ect", "ect").
ham_bigram("subject", "re").
ham_bigram("of", "the").
ham_bigram("enron", "enron").
ham_bigram("ect", "cc").
ham_bigram("pm", "to").
ham_bigram("for", "the").
ham_bigram("forwarded", "by").
ham_bigram("will", "be").
ham_bigram("corp", "enron").
ham_bigram("_", "_").
ham_bigram("if", "you").
ham_bigram("am", "to").
ham_bigram("on", "the").
ham_bigram("cc", "subject").
ham_bigram("in", "the").
ham_bigram("to", "the").
ham_bigram("daren", "j").
ham_bigram("let", "me").
ham_bigram("me", "know").
ham_bigram("enron", "com").
ham_bigram("ect", "on").
ham_bigram("j", "farmer").
ham_bigram("you", "have").
ham_bigram("ect", "subject").
ham_bigram("to", "be").
ham_bigram("need", "to").
ham_bigram("should", "be").
ham_bigram("farmer", "hou").
ham_bigram("mmbtu", "d").
ham_bigram("the", "following").
ham_bigram("i", "have").
ham_bigram("this", "is").
ham_bigram("have", "any").
ham_bigram("at", "the").
ham_bigram("any", "questions").
ham_bigram("is", "a").
ham_bigram("see", "attached").
ham_bigram("e", "mail").
ham_bigram("i", "will").
ham_bigram("attached", "file").
ham_bigram("xls", "subject").
ham_bigram("the", "deal").
ham_bigram("message", "from").
ham_bigram("please", "let").
ham_bigram("original", "message").
ham_bigram("with", "the").
ham_bigram("is", "the").
ham_bigram("know", "if").
ham_bigram("000", "mmbtu").
ham_bigram("i", "am").
ham_bigram("it", "is").
ham_bigram("we", "have").
ham_bigram("000", "enron").
ham_bigram("and", "the").
ham_bigram("has", "been").
ham_bigram("the", "gas").
ham_bigram("2000", "10").
ham_bigram("pec", "pec").
ham_bigram("we", "are").
ham_bigram("don", "t").
ham_bigram("enron", "on").
ham_bigram("teco", "tap").
ham_bigram("there", "is").
ham_bigram("subject", "hpl").
ham_bigram("have", "a").
ham_bigram("enron", "cc").
ham_bigram("from", "the").
ham_bigram("we", "will").
ham_bigram("enron", "subject").
ham_bigram("set", "up").
ham_bigram("that", "we").
ham_bigram("the", "month").
ham_bigram("gas", "daily").
ham_bigram("north", "america").
ham_bigram("subject", "fw").
ham_bigram("tenaska", "iv").
ham_bigram("thank", "you").
ham_bigram("you", "can").
ham_bigram("have", "been").
ham_bigram("that", "the").
ham_bigram("corp", "from").
ham_bigram("to", "get").
ham_bigram("enron", "north").
ham_bigram("vance", "l").
ham_bigram("robert", "cotten").
ham_bigram("ami", "chokshi").
ham_bigram("2000", "02").
ham_bigram("l", "taylor").
ham_bigram("to", "daren").
ham_bigram("2000", "03").
ham_bigram("pat", "clynes").
ham_bigram("on", "03").
ham_bigram("nom", "for").
ham_bigram("can", "you").
ham_bigram("2000", "09").
ham_bigram("robert", "e").
ham_bigram("e", "lloyd").
ham_bigram("2000", "11").
ham_bigram("america", "corp").
ham_bigram("melissa", "graves").
ham_bigram("for", "your").
ham_bigram("want", "to").
ham_bigram("you", "are").
ham_bigram("cotten", "hou").
ham_bigram("in", "sitara").
ham_bigram("na", "enron").
ham_bigram("hpl", "nom").
ham_bigram("2000", "teco").
ham_bigram("for", "this").
ham_bigram("i", "need").
ham_bigram("actuals", "for").
ham_bigram("that", "i").
ham_bigram("subject", "enron").
ham_bigram("i", "m").
ham_bigram("do", "not").
ham_bigram("we", "need").
ham_bigram("this", "deal").
ham_bigram("i", "can").
ham_bigram("clynes", "corp").
ham_bigram("and", "i").
ham_bigram("2000", "08").
ham_bigram("pg", "e").
ham_bigram("subject", "meter").
ham_bigram("aol", "com").
ham_bigram("the", "meter").
ham_bigram("on", "this").
ham_bigram("if", "hsc").
ham_bigram("is", "not").
ham_bigram("1", "00").
ham_bigram("of", "this").
ham_bigram("at", "this").
ham_bigram("this", "meter").
ham_bigram("30", "000").
ham_bigram("needs", "to").
ham_bigram("chokshi", "corp").
ham_bigram("the", "new").
ham_bigram("smith", "hou").
ham_bigram("aimee", "lannou").
ham_bigram("a", "deal").
ham_bigram("please", "call").
ham_bigram("com", "cc").
ham_bigram("at", "meter").
ham_bigram("enron", "hpl").
ham_bigram("texas", "utilities").
ham_bigram("10", "000").
ham_bigram("a", "new").
ham_bigram("would", "be").
ham_bigram("do", "you").
ham_bigram("on", "06").
ham_bigram("i", "would").
ham_bigram("you", "need").
ham_bigram("julie", "meyers").
ham_bigram("on", "a").
ham_bigram("the", "same").
ham_bigram("pefs", "pec").
ham_bigram("enron", "enronxgate").
ham_bigram("less", "0").
ham_bigram("would", "like").
ham_bigram("graves", "hou").
ham_bigram("gcs", "cec").
ham_bigram("cec", "pec").
ham_bigram("month", "of").
ham_bigram("2000", "01").
ham_bigram("x", "3").
ham_bigram("jackie", "young").
ham_bigram("all", "of").
ham_bigram("the", "attached").
ham_bigram("for", "a").
ham_bigram("hpl", "actuals").
ham_bigram("00", "pm").
ham_bigram("based", "on").
ham_bigram("on", "05").
ham_bigram("able", "to").
ham_bigram("by", "the").
ham_bigram("to", "do").
ham_bigram("to", "robert").
ham_bigram("call", "me").
ham_bigram("2000", "04").
ham_bigram("not", "be").
ham_bigram("have", "the").
ham_bigram("you", "will").
ham_bigram("lloyd", "hou").
ham_bigram("you", "please").
ham_bigram("like", "to").
ham_bigram("on", "04").
ham_bigram("utilities", "tu").
ham_bigram("natural", "gas").
ham_bigram("re", "meter").
ham_bigram("that", "you").
ham_bigram("due", "to").
ham_bigram("gary", "a").
ham_bigram("a", "hanks").
ham_bigram("20", "000").
ham_bigram("the", "plant").
ham_bigram("will", "need").
ham_bigram("com", "subject").
ham_bigram("george", "weissman").
ham_bigram("the", "volumes").
ham_bigram("deal", "ticket").
ham_bigram("the", "above").
ham_bigram("howard", "b").
ham_bigram("b", "camp").
ham_bigram("00", "am").
ham_bigram("questions", "please").
ham_bigram("we", "can").
ham_bigram("there", "are").
ham_bigram("the", "contract").
ham_bigram("as", "a").
ham_bigram("on", "02").
ham_bigram("hpl", "iferc").
ham_bigram("out", "of").
ham_bigram("to", "have").
ham_bigram("000", "hpl").
ham_bigram("meyers", "hou").
ham_bigram("the", "volume").
ham_bigram("the", "price").
ham_bigram("2000", "12").
ham_bigram("2001", "10").
ham_bigram("pm", "from").
ham_bigram("ect", "pat").
ham_bigram("for", "april").
ham_bigram("susan", "smith").
ham_bigram("to", "you").
ham_bigram("i", "don").
ham_bigram("taylor", "hou").
ham_bigram("camp", "hou").
ham_bigram("rita", "wynne").
ham_bigram("are", "not").
ham_bigram("the", "first").
ham_bigram("you", "know").
ham_bigram("ls", "hpl").
ham_bigram("so", "that").
ham_bigram("by", "ami").
ham_bigram("000", "d").
ham_bigram("they", "are").
ham_bigram("it", "s").
ham_bigram("28", "2000").
ham_bigram("on", "01").
ham_bigram("gas", "nomination").
ham_bigram("farmer", "daren").
ham_bigram("gco", "enron").
ham_bigram("to", "this").
ham_bigram("you", "want").
ham_bigram("will", "have").
ham_bigram("have", "to").
ham_bigram("flow", "for").
ham_bigram("lannou", "hou").
ham_bigram("for", "march").
ham_bigram("to", "make").
ham_bigram("will", "not").
ham_bigram("ect", "robert").
ham_bigram("of", "you").
ham_bigram("cotton", "valley").
ham_bigram("21", "2000").
ham_bigram("fuels", "cotton").
ham_bigram("you", "to").
ham_bigram("2000", "see").
ham_bigram("hpl", "gas").
ham_bigram("ect", "daren").
ham_bigram("know", "what").
ham_bigram("for", "july").
ham_bigram("but", "i").
ham_bigram("for", "may").
ham_bigram("nomination", "for").
ham_bigram("as", "well").
ham_bigram("as", "follows").
ham_bigram("this", "gas").
ham_bigram("22", "2000").
ham_bigram("on", "08").
ham_bigram("that", "this").
ham_bigram("wynne", "hou").
ham_bigram("could", "you").
ham_bigram("1", "2000").
ham_bigram("in", "a").
ham_bigram("change", "the").
ham_bigram("tom", "acton").
ham_bigram("10", "00").
ham_bigram("me", "to").
ham_bigram("10", "2000").
ham_bigram("i", "think").
ham_bigram("attached", "is").
ham_bigram("the", "system").
ham_bigram("going", "to").
ham_bigram("can", "be").
ham_bigram("when", "you").
ham_bigram("hanks", "hou").
ham_bigram("thanks", "for").
ham_bigram("that", "is").
ham_bigram("com", "on").
ham_bigram("doc", "subject").
ham_bigram("hotmail", "com").
ham_bigram("and", "will").
ham_bigram("to", "your").
ham_bigram("to", "me").
ham_bigram("hsc", "less").
ham_bigram("donald", "p").
ham_bigram("young", "hou").
ham_bigram("and", "a").
ham_bigram("weissman", "hou").
ham_bigram("and", "we").
ham_bigram("with", "a").
ham_bigram("ect", "melissa").
ham_bigram("anita", "luong").
ham_bigram("you", "for").
ham_bigram("melissa", "jones").
ham_bigram("created", "and").
ham_bigram("p", "reinhardt").
ham_bigram("deal", "for").
ham_bigram("11", "2000").
ham_bigram("daren", "i").
ham_bigram("i", "ll").
ham_bigram("end", "of").
ham_bigram("hpl", "lsk").
ham_bigram("ect", "mary").
ham_bigram("on", "hpl").
ham_bigram("2001", "at").
ham_bigram("2000", "05").
ham_bigram("2001", "see").
ham_bigram("did", "not").
ham_bigram("continue", "to").
ham_bigram("vlt", "x").
ham_bigram("be", "able").
ham_bigram("in", "your").
ham_bigram("into", "the").
ham_bigram("http", "www").
ham_bigram("be", "a").
ham_bigram("with", "this").
ham_bigram("lsk", "ic").
ham_bigram("to", "see").
ham_bigram("ect", "enron").
ham_bigram("duke", "energy").
ham_bigram("carlos", "j").
ham_bigram("j", "rodriguez").
ham_bigram("on", "12").
ham_bigram("if", "there").
ham_bigram("soon", "as").
ham_bigram("daren", "farmer").
ham_bigram("as", "soon").
ham_bigram("if", "the").
ham_bigram("actual", "flow").
ham_bigram("see", "the").
ham_bigram("31", "2000").
ham_bigram("please", "advise").
ham_bigram("5", "000").
ham_bigram("thanks", "subject").
ham_bigram("one", "of").
ham_bigram("to", "a").
ham_bigram("and", "entered").
ham_bigram("as", "the").
ham_bigram("for", "gas").
ham_bigram("oil", "gas").
ham_bigram("if", "this").
ham_bigram("a", "call").
ham_bigram("make", "sure").
ham_bigram("for", "you").
ham_bigram("lee", "l").
ham_bigram("l", "papayoti").
ham_bigram("daily", "gas").
ham_bigram("01", "2000").
ham_bigram("up", "to").
ham_bigram("deal", "is").
ham_bigram("charlie", "stone").
ham_bigram("a", "allen").
ham_bigram("megan", "parker").
ham_bigram("20", "2000").
ham_bigram("file", "hplno").
ham_bigram("xls", "hplno").
ham_bigram("july", "2000").
ham_bigram("from", "fuels").
ham_bigram("3", "6353").
ham_bigram("here", "is").
ham_bigram("back", "to").
ham_bigram("d", "100").
ham_bigram("07", "2000").
ham_bigram("05", "01").
ham_bigram("27", "2000").
ham_bigram("under", "the").
ham_bigram("if", "we").
ham_bigram("calpine", "daily").
ham_bigram("brenda", "f").
ham_bigram("f", "herod").
ham_bigram("may", "be").
ham_bigram("ect", "susan").
ham_bigram("mary", "poorman").
ham_bigram("19", "2000").
ham_bigram("on", "10").
ham_bigram("for", "june").
ham_bigram("sent", "thursday").
ham_bigram("cc", "daren").
ham_bigram("is", "to").
ham_bigram("lauri", "a").
ham_bigram("the", "next").
ham_bigram("it", "will").
ham_bigram("by", "robert").
ham_bigram("for", "all").
ham_bigram("06", "2000").
ham_bigram("if", "i").
ham_bigram("are", "the").
ham_bigram("100", "if").
ham_bigram("gas", "control").
ham_bigram("to", "david").
ham_bigram("megan", "subject").
ham_bigram("12", "2000").
ham_bigram("from", "robert").
ham_bigram("hpl", "meter").
ham_bigram("sherlyn", "schumack").
ham_bigram("mmbtu", "dy").
ham_bigram("for", "december").
ham_bigram("please", "see").
ham_bigram("reinhardt", "hou").
ham_bigram("list", "of").
ham_bigram("00", "00").
ham_bigram("in", "this").
ham_bigram("23", "2000").
ham_bigram("bob", "subject").
ham_bigram("does", "not").
ham_bigram("26", "2000").
ham_bigram("about", "the").
ham_bigram("it", "was").
ham_bigram("of", "your").
ham_bigram("29", "2000").
ham_bigram("to", "change").
ham_bigram("next", "week").
ham_bigram("please", "contact").
ham_bigram("the", "office").
ham_bigram("9", "00").
ham_bigram("that", "they").
ham_bigram("in", "order").
ham_bigram("you", "may").
ham_bigram("am", "enron").
ham_bigram("all", "the").
ham_bigram("me", "at").
ham_bigram("2001", "11").
ham_bigram("the", "end").
ham_bigram("enserch", "us").
ham_bigram("subject", "tenaska").
ham_bigram("into", "sitara").
ham_bigram("counterparty", "meter").
ham_bigram("some", "of").
ham_bigram("give", "me").
ham_bigram("me", "a").
ham_bigram("for", "january").
ham_bigram("jones", "texas").
ham_bigram("acton", "corp").
ham_bigram("6", "00").
ham_bigram("to", "cc").
ham_bigram("in", "addition").
ham_bigram("03", "2000").
ham_bigram("of", "our").
ham_bigram("ect", "howard").
ham_bigram("wanted", "to").
ham_bigram("on", "07").
ham_bigram("this", "will").
ham_bigram("not", "have").
ham_bigram("lsp", "enserch").
ham_bigram("for", "august").
ham_bigram("ect", "lisa").
ham_bigram("lisa", "hesse").
ham_bigram("your", "help").
ham_bigram("713", "830").
ham_bigram("over", "the").
ham_bigram("which", "is").
ham_bigram("shut", "in").
ham_bigram("the", "sale").
ham_bigram("dfarmer", "enron").
ham_bigram("gary", "w").
ham_bigram("w", "lamphier").
ham_bigram("this", "issue").
ham_bigram("during", "the").
ham_bigram("09", "2000").
ham_bigram("thanks", "vlt").
ham_bigram("look", "at").
ham_bigram("sale", "to").
ham_bigram("in", "place").
ham_bigram("so", "i").
ham_bigram("albrecht", "4").
ham_bigram("for", "2").
ham_bigram("questions", "or").
ham_bigram("what", "you").
ham_bigram("gas", "from").
ham_bigram("15", "000").
ham_bigram("herod", "hou").
ham_bigram("file", "hplo").
ham_bigram("xls", "hplo").
ham_bigram("as", "possible").
ham_bigram("demand", "fee").
ham_bigram("should", "have").
ham_bigram("hpl", "s").
ham_bigram("of", "a").
ham_bigram("hesse", "hou").
ham_bigram("prior", "to").
ham_bigram("to", "hpl").
ham_bigram("enron", "s").
ham_bigram("pm", "enron").
ham_bigram("25", "2000").
ham_bigram("allocated", "to").
ham_bigram("noms", "actual").
ham_bigram("allen", "hou").
ham_bigram("mary", "subject").
ham_bigram("get", "a").
ham_bigram("us", "tu").
ham_bigram("ect", "donald").
ham_bigram("clem", "cernosek").
ham_bigram("fred", "boas").
ham_bigram("13", "2000").
ham_bigram("lone", "star").
ham_bigram("on", "11").
ham_bigram("get", "the").
ham_bigram("sitara", "deal").
ham_bigram("for", "1").
ham_bigram("2001", "04").
ham_bigram("am", "from").
ham_bigram("new", "deal").
ham_bigram("part", "of").
ham_bigram("volume", "management").
ham_bigram("2000", "activity").
ham_bigram("to", "cover").
ham_bigram("2000", "07").
ham_bigram("entered", "into").
ham_bigram("david", "baumbach").
ham_bigram("713", "853").
ham_bigram("a", "price").
ham_bigram("have", "not").
ham_bigram("per", "day").
ham_bigram("we", "should").
ham_bigram("15", "2000").
ham_bigram("in", "pops").
ham_bigram("david", "avila").
ham_bigram("sent", "tuesday").
ham_bigram("into", "hpl").
ham_bigram("redeliveries", "will").
ham_bigram("subject", "revised").
ham_bigram("mark", "mccoy").
ham_bigram("easttexas", "pefs").
ham_bigram("your", "order").
ham_bigram("the", "time").
ham_bigram("18", "2000").
ham_bigram("order", "to").
ham_bigram("for", "meter").
ham_bigram("meter", "098").
ham_bigram("stone", "texas").
ham_bigram("liz", "bellamy").
ham_bigram("attached", "to").
ham_bigram("gpgfin", "enron").
ham_bigram("o", "neal").
ham_bigram("ect", "gary").
ham_bigram("the", "purchase").
ham_bigram("please", "note").
ham_bigram("16", "2000").
ham_bigram("of", "these").
ham_bigram("25", "000").
ham_bigram("2000", "and").
ham_bigram("this", "email").
ham_bigram("it", "to").
ham_bigram("to", "ami").
ham_bigram("to", "know").
ham_bigram("trying", "to").
ham_bigram("papayoti", "hou").
ham_bigram("these", "volumes").
ham_bigram("with", "you").
ham_bigram("deal", "tickets").
ham_bigram("i", "ve").
ham_bigram("i", "know").
ham_bigram("avila", "lsp").
ham_bigram("on", "09").
ham_bigram("the", "information").
ham_bigram("of", "enron").
ham_bigram("on", "deal").
ham_bigram("17", "2000").
ham_bigram("el", "paso").
ham_bigram("to", "take").
ham_bigram("katherine", "herrera").
ham_bigram("march", "2001").
ham_bigram("on", "your").
ham_bigram("sent", "friday").
ham_bigram("as", "you").
ham_bigram("00", "and").
ham_bigram("luong", "hou").
ham_bigram("for", "3").
ham_bigram("these", "deals").
ham_bigram("and", "he").
ham_bigram("the", "texas").
ham_bigram("com", "sent").
ham_bigram("12", "00").
ham_bigram("well", "as").
ham_bigram("24", "2000").
ham_bigram("that", "are").
ham_bigram("7", "00").
ham_bigram("go", "to").
ham_bigram("is", "an").
ham_bigram("for", "october").
ham_bigram("be", "the").
ham_bigram("thanks", "jackie").
ham_bigram("coastal", "oil").
ham_bigram("to", "our").
ham_bigram("through", "the").
ham_bigram("is", "now").
ham_bigram("the", "gathering").
ham_bigram("each", "of").
ham_bigram("you", "think").
ham_bigram("out", "the").
ham_bigram("deal", "in").
ham_bigram("04", "2000").
ham_bigram("reliantenergy", "com").
ham_bigram("gas", "to").
ham_bigram("sent", "monday").
ham_bigram("for", "5").
ham_bigram("is", "on").
ham_bigram("gas", "sales").
ham_bigram("at", "a").
ham_bigram("tu", "charlie").
ham_bigram("subject", "new").
ham_bigram("march", "2000").
ham_bigram("deals", "for").
ham_bigram("2001", "02").
ham_bigram("and", "it").
ham_bigram("p", "l").
ham_bigram("and", "should").
ham_bigram("lamphier", "hou").
ham_bigram("the", "last").
ham_bigram("3", "9497").
ham_bigram("what", "is").
ham_bigram("05", "2000").
ham_bigram("know", "thanks").
ham_bigram("i", "was").
ham_bigram("eileen", "ponton").
ham_bigram("tu", "melissa").
ham_bigram("enronxgate", "on").
ham_bigram("price", "for").
ham_bigram("enron", "corp").
ham_bigram("questions", "thanks").
ham_bigram("will", "continue").
ham_bigram("jackie", "3").
ham_bigram("2001", "12").
ham_bigram("for", "9").
ham_bigram("m", "smith").
ham_bigram("brian", "m").
ham_bigram("m", "riley").
ham_bigram("and", "let").
ham_bigram("about", "this").
ham_bigram("for", "these").
ham_bigram("the", "demand").
ham_bigram("wellhead", "portfolio").
ham_bigram("for", "each").
ham_bigram("21", "2001").
ham_bigram("2001", "03").
ham_bigram("so", "we").
ham_bigram("of", "any").
ham_bigram("deliveries", "to").
ham_bigram("the", "redeliveries").
ham_bigram("didn", "t").
ham_bigram("1", "99").
ham_bigram("is", "that").
ham_bigram("thanks", "megan").
ham_bigram("cynthia", "hakemack").
ham_bigram("sitara", "based").
ham_bigram("im", "wellhead").
ham_bigram("may", "2001").
ham_bigram("the", "hpl").
ham_bigram("if", "it").
ham_bigram("2001", "01").
ham_bigram("request", "for").
ham_bigram("that", "will").
ham_bigram("is", "in").
ham_bigram("we", "agree").
ham_bigram("deal", "number").
ham_bigram("2000", "the").
ham_bigram("noms", "for").
ham_bigram("meter", "1266").
ham_bigram("schumack", "hou").
ham_bigram("path", "manager").
ham_bigram("30", "2000").
ham_bigram("riley", "hou").
ham_bigram("5", "00").
ham_bigram("is", "this").
ham_bigram("to", "keep").
ham_bigram("as", "i").
ham_bigram("the", "only").
ham_bigram("up", "the").
ham_bigram("for", "10").
ham_bigram("for", "february").
ham_bigram("cc", "robert").
ham_bigram("12", "99").
ham_bigram("d", "h").
ham_bigram("4", "well").
ham_bigram("ponton", "on").
ham_bigram("bellamy", "enron").
ham_bigram("mary", "m").
ham_bigram("ect", "michael").
ham_bigram("40", "000").
ham_bigram("for", "me").
ham_bigram("mmbtu", "per").
ham_bigram("a", "few").
ham_bigram("to", "julie").
ham_bigram("the", "best").
ham_bigram("the", "nom").
ham_bigram("00", "production").
ham_bigram("volumes", "to").
ham_bigram("can", "t").
ham_bigram("a", "spot").
ham_bigram("regarding", "the").
ham_bigram("hpl", "scheduling").
ham_bigram("gathering", "contract").
ham_bigram("rodriguez", "hou").
ham_bigram("stephanie", "gomes").
ham_bigram("i", "believe").
ham_bigram("stacey", "neuweiler").
ham_bigram("subject", "cornhusker").
ham_bigram("into", "eastrans").
ham_bigram("know", "when").
ham_bigram("allocation", "exception").
ham_bigram("a", "m").
ham_bigram("up", "for").
ham_bigram("t", "have").
ham_bigram("in", "our").
ham_bigram("hakemack", "hou").
ham_bigram("baumbach", "hou").
ham_bigram("the", "other").
ham_bigram("sent", "wednesday").
ham_bigram("you", "would").
ham_bigram("to", "go").
ham_bigram("11", "01").
ham_bigram("get", "this").
ham_bigram("was", "not").
ham_bigram("t", "know").
ham_bigram("gas", "corporation").
ham_bigram("let", "you").
ham_bigram("deal", "and").
ham_bigram("to", "gary").
ham_bigram("has", "not").
ham_bigram("parker", "corp").
ham_bigram("8", "00").
ham_bigram("yahoo", "com").
ham_bigram("be", "in").
ham_bigram("what", "the").
ham_bigram("subject", "nom").
ham_bigram("eastrans", "nomination").
ham_bigram("we", "would").
ham_bigram("according", "to").
ham_bigram("31", "st").
ham_bigram("there", "was").
ham_bigram("to", "discuss").
ham_bigram("steve", "holmes").
ham_bigram("to", "help").
ham_bigram("gas", "company").
ham_bigram("this", "time").
ham_bigram("but", "the").
ham_bigram("scheduling", "enron").
ham_bigram("com", "liz").
ham_bigram("ticket", "for").
ham_bigram("ect", "george").
ham_bigram("earl", "tisdale").
ham_bigram("2001", "08").
ham_bigram("for", "tenaska").
ham_bigram("hpl", "to").
ham_bigram("thanks", "bob").
ham_bigram("gas", "at").
ham_bigram("the", "transport").
ham_bigram("6353", "subject").
ham_bigram("to", "call").
ham_bigram("the", "deals").
ham_bigram("in", "unify").
ham_bigram("copy", "of").
ham_bigram("for", "november").
ham_bigram("14", "2000").
ham_bigram("bob", "forwarded").
ham_bigram("to", "aimee").
ham_bigram("24", "2001").
ham_bigram("tina", "valadez").
ham_bigram("purchase", "from").
ham_bigram("ua", "4").
ham_bigram("and", "is").
ham_bigram("30", "am").
ham_bigram("subject", "calpine").
ham_bigram("at", "713").
ham_bigram("a", "copy").
ham_bigram("forward", "to").
ham_bigram("to", "jackie").
ham_bigram("4", "00").
ham_bigram("we", "do").
ham_bigram("the", "current").
ham_bigram("free", "to").
ham_bigram("i", "do").
ham_bigram("sales", "on").
ham_bigram("for", "sept").
ham_bigram("to", "reflect").
ham_bigram("that", "it").
ham_bigram("must", "be").
ham_bigram("a", "ticket").
ham_bigram("be", "created").
ham_bigram("26", "2001").
ham_bigram("need", "a").
ham_bigram("713", "345").
ham_bigram("deal", "was").
ham_bigram("a", "list").
ham_bigram("subject", "eastrans").
ham_bigram("i", "spoke").
ham_bigram("deal", "to").
ham_bigram("08", "09").
ham_bigram("re", "deal").
ham_bigram("not", "been").
ham_bigram("know", "that").
ham_bigram("with", "any").
ham_bigram("2001", "09").
ham_bigram("the", "correct").
ham_bigram("with", "your").
ham_bigram("april", "2001").
ham_bigram("had", "a").
ham_bigram("to", "work").
ham_bigram("this", "e").
ham_bigram("may", "not").
ham_bigram("mobil", "beaumont").
ham_bigram("they", "have").
ham_bigram("as", "we").
ham_bigram("please", "forward").
ham_bigram("the", "sitara").
ham_bigram("by", "gary").
ham_bigram("volume", "is").
ham_bigram("feel", "free").
ham_bigram("cp", "l").
ham_bigram("on", "line").
ham_bigram("ect", "james").
ham_bigram("please", "do").
ham_bigram("not", "sure").
ham_bigram("volume", "of").
ham_bigram("and", "or").
ham_bigram("04", "01").
ham_bigram("the", "transaction").
ham_bigram("to", "enron").
ham_bigram("unaccounted", "for").
ham_bigram("31", "00").
ham_bigram("14", "2001").
ham_bigram("this", "message").
ham_bigram("any", "other").
ham_bigram("tu", "hpl").
ham_bigram("been", "created").
ham_bigram("please", "review").
ham_bigram("december", "2000").
ham_bigram("houston", "texas").
ham_bigram("additional", "information").
ham_bigram("click", "on").
ham_bigram("is", "for").
ham_bigram("spoke", "with").
ham_bigram("extend", "the").
ham_bigram("effective", "6").
ham_bigram("enron", "_").
ham_bigram("_", "development").
ham_bigram("what", "we").
ham_bigram("file", "hplnl").
ham_bigram("xls", "hplnl").
ham_bigram("first", "delivery").
ham_bigram("ticket", "should").
ham_bigram("james", "mckay").
ham_bigram("and", "may").
ham_bigram("farmer", "enron").
ham_bigram("to", "handle").
ham_bigram("60", "000").
ham_bigram("these", "are").
ham_bigram("of", "2").
ham_bigram("do", "we").
ham_bigram("for", "september").
ham_bigram("you", "get").
ham_bigram("i", "just").
ham_bigram("this", "morning").
ham_bigram("16", "2001").
ham_bigram("a", "little").
ham_bigram("here", "are").
ham_bigram("that", "was").
ham_bigram("13", "2001").
ham_bigram("this", "point").
ham_bigram("co", "tx").
ham_bigram("to", "receive").
ham_bigram("23", "2001").
ham_bigram("ect", "vance").
ham_bigram("not", "a").
ham_bigram("priced", "at").
ham_bigram("2", "00").
ham_bigram("the", "company").
ham_bigram("meter", "for").
ham_bigram("50", "000").
ham_bigram("3", "2001").
ham_bigram("deals", "in").
ham_bigram("by", "daren").
ham_bigram("subject", "noms").
ham_bigram("the", "im").
ham_bigram("king", "ranch").
ham_bigram("october", "2000").
ham_bigram("to", "look").
ham_bigram("has", "a").
ham_bigram("this", "to").
ham_bigram("listed", "below").
ham_bigram("price", "of").
ham_bigram("changes", "to").
ham_bigram("for", "03").
ham_bigram("pipe", "line").
ham_bigram("enron", "capital").
ham_bigram("how", "to").
ham_bigram("at", "carthage").
ham_bigram("11", "3").
ham_bigram("098", "4179").
ham_bigram("and", "if").
ham_bigram("use", "the").
ham_bigram("22", "2001").
ham_bigram("couple", "of").
ham_bigram("1", "2001").
ham_bigram("on", "to").
ham_bigram("is", "being").
ham_bigram("and", "you").
ham_bigram("the", "enron").
ham_bigram("500", "mmbtu").
ham_bigram("to", "set").
ham_bigram("approval", "to").
ham_bigram("5", "th").
ham_bigram("would", "you").
ham_bigram("2000", "i").
ham_bigram("it", "has").
ham_bigram("to", "d").
ham_bigram("be", "tracked").
ham_bigram("tracked", "in").
ham_bigram("portfolio", "attached").
ham_bigram("25", "2001").
ham_bigram("boas", "hou").
ham_bigram("take", "a").
ham_bigram("note", "that").
ham_bigram("chokshi", "enron").
ham_bigram("meter", "is").
ham_bigram("can", "we").
ham_bigram("following", "information").
ham_bigram("was", "a").
ham_bigram("responsible", "for").
ham_bigram("i", "had").
ham_bigram("strangers", "gas").
ham_bigram("fyi", "forwarded").
ham_bigram("are", "as").
ham_bigram("ect", "rita").
ham_bigram("be", "allocated").
ham_bigram("a", "problem").
ham_bigram("bob", "m").
ham_bigram("me", "if").
ham_bigram("you", "re").
ham_bigram("we", "ll").
ham_bigram("iferc", "ls").
ham_bigram("to", "all").
ham_bigram("the", "supply").
ham_bigram("file", "hpl").
ham_bigram("the", "ena").
ham_bigram("03", "01").
ham_bigram("nomination", "change").
ham_bigram("sure", "that").
ham_bigram("volumes", "are").
ham_bigram("bruce", "mcmills").
ham_bigram("know", "the").
ham_bigram("morris", "hou").
ham_bigram("sent", "to").
ham_bigram("that", "he").
ham_bigram("aep", "com").
ham_bigram("on", "monday").
ham_bigram("term", "of").
ham_bigram("producer", "svcs").
ham_bigram("mckay", "hou").
ham_bigram("poorman", "na").
ham_bigram("august", "2000").
ham_bigram("gas", "marketing").
ham_bigram("until", "the").
ham_bigram("create", "a").
ham_bigram("xls", "hpl").
ham_bigram("1", "doc").
ham_bigram("at", "http").
ham_bigram("to", "ensure").
ham_bigram("agree", "with").
ham_bigram("to", "eastrans").
ham_bigram("i", "did").
ham_bigram("them", "to").
ham_bigram("the", "day").
ham_bigram("for", "our").
ham_bigram("for", "an").
ham_bigram("to", "unaccounted").
ham_bigram("volume", "price").
ham_bigram("victor", "lamadrid").
ham_bigram("03", "21").
ham_bigram("houston", "pefs").
ham_bigram("and", "then").
ham_bigram("the", "total").
ham_bigram("to", "send").
ham_bigram("gas", "on").
ham_bigram("to", "pay").
ham_bigram("it", "would").
ham_bigram("beverly", "beaty").
ham_bigram("45", "pm").
ham_bigram("in", "my").
ham_bigram("mmbtu", "s").
ham_bigram("you", "and").
ham_bigram("this", "was").
ham_bigram("be", "on").
ham_bigram("stella", "l").
ham_bigram("expedia", "com").
ham_bigram("00", "463").
ham_bigram("463", "2").

% Kiểm tra email có phải spam hay ham
classify_email(Text, Result, SpamPercent, HamPercent) :-
    split_string(Text, " ", "", Words),
    findall((W1, W2), (nth0(I, Words, W1), nth0(J, Words, W2), J is I + 1, spam_bigram(W1, W2)), SpamBigrams),
    findall((W1, W2), (nth0(I, Words, W1), nth0(J, Words, W2), J is I + 1, ham_bigram(W1, W2)), HamBigrams),
    length(SpamBigrams, SpamCount),
    length(HamBigrams, HamCount),
    Total is SpamCount + HamCount,
    (Total > 0 ->
            SpamPercent is (SpamCount / Total) * 100,
            HamPercent is (HamCount / Total) * 100;
            SpamPercent = 0.0,
            HamPercent = 0.0
    ),
    (SpamCount > HamCount -> Result = "spam"; Result = "ham").