% Top spam words
spam_word("the").
spam_word("to").
spam_word("and").
spam_word("of").
spam_word("a").
spam_word("in").
spam_word("you").
spam_word("for").
spam_word("this").
spam_word("is").
spam_word("your").
spam_word("subject").
spam_word("with").
spam_word("that").
spam_word("s").
spam_word("be").
spam_word("or").
spam_word("on").
spam_word("3").
spam_word("_").
spam_word("as").
spam_word("are").
spam_word("we").
spam_word("i").
spam_word("it").
spam_word("not").
spam_word("our").
spam_word("com").
spam_word("http").
spam_word("from").
spam_word("have").
spam_word("all").
spam_word("2").
spam_word("no").
spam_word("at").
spam_word("company").
spam_word("1").
spam_word("0").
spam_word("will").
spam_word("by").
spam_word("e").
spam_word("can").
spam_word("an").
spam_word("more").
spam_word("here").
spam_word("www").
spam_word("00").
spam_word("any").
spam_word("if").
spam_word("information").
spam_word("font").
spam_word("me").
spam_word("5").
spam_word("t").
spam_word("only").
spam_word("td").
spam_word("4").
spam_word("has").
spam_word("get").
spam_word("please").
spam_word("statements").
spam_word("d").
spam_word("email").
spam_word("price").
spam_word("us").
spam_word("7").
spam_word("new").
spam_word("may").
spam_word("nbsp").
spam_word("my").
spam_word("one").
spam_word("p").
spam_word("do").
spam_word("now").
spam_word("was").
spam_word("up").
spam_word("height").
spam_word("time").
spam_word("its").
spam_word("out").
spam_word("these").
spam_word("8").
spam_word("99").
spam_word("o").
spam_word("within").
spam_word("free").
spam_word("pills").
spam_word("6").
spam_word("r").
spam_word("size").
spam_word("width").
spam_word("but").
spam_word("about").
spam_word("over").
spam_word("stock").
spam_word("2004").
spam_word("b").
spam_word("10").
spam_word("message").
spam_word("money").
spam_word("other").
spam_word("investment").
spam_word("m").
spam_word("which").
spam_word("9").
spam_word("c").
spam_word("u").
spam_word("report").
spam_word("their").
spam_word("inc").
spam_word("been").
spam_word("just").
spam_word("securities").
spam_word("online").
spam_word("business").
spam_word("click").
spam_word("looking").
spam_word("best").
spam_word("there").
spam_word("100").
spam_word("what").
spam_word("000").
spam_word("60").
spam_word("like").
spam_word("contact").
spam_word("mail").
spam_word("computron").
spam_word("so").
spam_word("prices").
spam_word("align").
spam_word("re").
spam_word("future").
spam_word("tr").
spam_word("15").
spam_word("x").
spam_word("news").
spam_word("need").
spam_word("20").
spam_word("products").
spam_word("v").
spam_word("net").
spam_word("into").
spam_word("save").
spam_word("go").
spam_word("want").
spam_word("n").
spam_word("use").
spam_word("forward").
spam_word("many").
spam_word("also").
spam_word("windows").
spam_word("microsoft").
spam_word("today").
spam_word("would").
spam_word("color").
spam_word("they").
spam_word("50").
spam_word("international").
spam_word("th").
spam_word("million").
spam_word("software").
spam_word("link").
spam_word("69").
spam_word("face").
spam_word("most").
spam_word("border").
spam_word("internet").
spam_word("than").
spam_word("without").
spam_word("market").
spam_word("make").
spam_word("account").
spam_word("available").
spam_word("href").
spam_word("line").
spam_word("professional").
spam_word("g").
spam_word("info").
spam_word("high").
spam_word("could").
spam_word("l").
spam_word("such").
spam_word("should").
spam_word("companies").
spam_word("see").
spam_word("viagra").
spam_word("office").
spam_word("order").
spam_word("world").
spam_word("how").
spam_word("95").
spam_word("br").
spam_word("through").
spam_word("90").
spam_word("some").
spam_word("gas").
spam_word("before").
spam_word("act").
spam_word("number").
spam_word("30").
spam_word("when").
spam_word("reply").
spam_word("xp").
spam_word("stocks").
spam_word("product").
spam_word("take").
spam_word("adobe").
spam_word("offer").
spam_word("special").
spam_word("address").
spam_word("src").
spam_word("site").
spam_word("service").
spam_word("25").
spam_word("don").
spam_word("who").
spam_word("advice").
spam_word("back").
spam_word("first").
spam_word("stop").
spam_word("he").
spam_word("nd").
spam_word("results").
spam_word("remove").
spam_word("pt").
spam_word("his").
spam_word("low").
spam_word("f").
spam_word("section").
spam_word("based").
spam_word("system").
spam_word("cialis").
spam_word("63").
spam_word("made").
spam_word("know").
spam_word("oil").
spam_word("home").
spam_word("visit").
spam_word("shares").
spam_word("security").
spam_word("80").
spam_word("them").
spam_word("center").
spam_word("very").
spam_word("send").
spam_word("energy").
spam_word("after").
spam_word("soft").
spam_word("12").
spam_word("performance").
spam_word("2003").
spam_word("161").
spam_word("own").
spam_word("sent").
spam_word("list").
spam_word("services").
spam_word("h").
spam_word("prescription").
spam_word("dollars").
spam_word("120").
spam_word("year").
spam_word("buy").
spam_word("day").
spam_word("below").
spam_word("off").
spam_word("meds").
spam_word("newsletter").
spam_word("phone").
spam_word("11").
spam_word("html").
spam_word("next").
spam_word("y").
spam_word("even").
spam_word("two").
spam_word("am").
spam_word("long").
spam_word("style").
spam_word("had").
spam_word("family").
spam_word("days").
spam_word("were").
spam_word("said").
spam_word("being").
spam_word("sales").
spam_word("works").
spam_word("hours").
spam_word("per").
spam_word("people").
spam_word("quality").
spam_word("24").
spam_word("well").
spam_word("good").
spam_word("name").
spam_word("full").
spam_word("top").
spam_word("receive").
spam_word("cd").
spam_word("paliourg").
spam_word("does").
spam_word("she").
spam_word("because").
spam_word("fact").
spam_word("investing").
spam_word("every").
spam_word("40").
spam_word("find").
spam_word("due").
spam_word("limited").
spam_word("offers").
spam_word("voip").
spam_word("interest").
spam_word("ms").
spam_word("de").
spam_word("details").
spam_word("above").
spam_word("w").
spam_word("pro").
spam_word("great").
spam_word("same").
spam_word("via").
spam_word("ve").
spam_word("events").
spam_word("45").
spam_word("then").
spam_word("life").
spam_word("oo").
spam_word("technology").
spam_word("last").
spam_word("fax").
spam_word("index").
spam_word("php").
spam_word("health").
spam_word("sale").
spam_word("much").
spam_word("bgcolor").
spam_word("part").
spam_word("under").
spam_word("mg").
spam_word("real").
spam_word("those").
spam_word("look").
spam_word("drugs").
spam_word("china").
spam_word("read").
spam_word("hi").
spam_word("44").
spam_word("k").
spam_word("right").
spam_word("shipping").
spam_word("group").
spam_word("trade").
spam_word("include").
spam_word("less").
spam_word("industry").
spam_word("including").
spam_word("registered").
spam_word("strong").
spam_word("check").
spam_word("her").
spam_word("easy").
spam_word("way").
spam_word("further").
spam_word("2005").
spam_word("month").
spam_word("help").
spam_word("pain").
spam_word("past").
spam_word("provided").
spam_word("pay").
spam_word("week").
spam_word("customers").
spam_word("work").
spam_word("copy").
spam_word("risks").
spam_word("process").
spam_word("content").
spam_word("gif").
spam_word("watch").
spam_word("must").
spam_word("believe").
spam_word("where").
spam_word("mobile").
spam_word("biz").
spam_word("thank").
spam_word("web").
spam_word("expectations").
spam_word("cs").
spam_word("states").
spam_word("wish").
spam_word("give").
spam_word("come").
spam_word("notice").
spam_word("spam").
spam_word("cost").
spam_word("material").
spam_word("better").
spam_word("current").
spam_word("21").
spam_word("party").
spam_word("change").
spam_word("weight").
spam_word("development").
spam_word("sell").
spam_word("14").
spam_word("always").
spam_word("ali").
spam_word("duty").
spam_word("cash").
spam_word("tabs").
spam_word("regards").
spam_word("private").
spam_word("canada").
spam_word("cause").
spam_word("differ").
spam_word("publisher").
spam_word("thanks").
spam_word("text").
spam_word("retail").
spam_word("management").
spam_word("bank").
spam_word("never").
spam_word("place").
spam_word("again").
spam_word("removed").
spam_word("while").
spam_word("growth").
spam_word("971").
spam_word("download").
spam_word("transfer").
spam_word("ll").
spam_word("financial").
spam_word("why").
spam_word("united").
spam_word("mx").
spam_word("124").
spam_word("photoshop").
spam_word("using").
spam_word("needed").
spam_word("yourself").
spam_word("risk").
spam_word("major").
spam_word("drive").
spam_word("each").
spam_word("country").
spam_word("img").
spam_word("cheap").
spam_word("uncertainties").
spam_word("compliance").
spam_word("70").
spam_word("browser").
spam_word("man").
spam_word("body").
spam_word("valign").
spam_word("ever").
spam_word("going").
spam_word("action").
spam_word("third").
spam_word("target").
spam_word("feel").
spam_word("2000").
spam_word("technologies").
spam_word("increase").
spam_word("worldwide").
spam_word("brand").
spam_word("terms").
spam_word("press").
spam_word("required").
spam_word("super").
spam_word("sex").
spam_word("program").
spam_word("years").
spam_word("computer").
spam_word("men").
spam_word("call").
spam_word("st").
spam_word("used").
spam_word("lose").
spam_word("32").
spam_word("server").
spam_word("000000").
spam_word("rate").
spam_word("sources").
spam_word("keep").
spam_word("credit").
spam_word("mr").
spam_word("div").
spam_word("meaning").
spam_word("publication").
spam_word("since").
spam_word("little").
spam_word("unsubscribe").
spam_word("paste").
spam_word("let").
spam_word("love").
spam_word("table").
spam_word("jpg").
spam_word("moopid").
spam_word("hotlist").
spam_word("estimates").
spam_word("featured").
spam_word("17").
spam_word("down").
spam_word("federal").
spam_word("middle").
spam_word("total").
spam_word("source").
spam_word("subscribers").
spam_word("release").
spam_word("16").
spam_word("city").
spam_word("01").
spam_word("generic").
spam_word("pharmacy").
spam_word("power").
spam_word("projections").
spam_word("customer").
spam_word("investors").
spam_word("epson").
spam_word("second").
spam_word("try").
spam_word("loss").
spam_word("certain").
spam_word("set").
spam_word("review").
spam_word("natural").
spam_word("follow").
spam_word("date").
spam_word("rates").
spam_word("access").
spam_word("paid").
spam_word("27").
spam_word("prior").
spam_word("position").
spam_word("move").
spam_word("three").
spam_word("show").
spam_word("considered").
spam_word("suite").
spam_word("america").
spam_word("gr").
spam_word("xanax").
spam_word("htmlimg").
spam_word("got").
spam_word("property").
spam_word("public").
spam_word("area").
spam_word("provide").
spam_word("large").
spam_word("images").
spam_word("too").
spam_word("colspan").
spam_word("involve").
spam_word("readers").
spam_word("kind").
spam_word("hot").
spam_word("support").
spam_word("additional").
spam_word("view").
spam_word("thousand").
spam_word("project").
spam_word("19").
spam_word("36").
spam_word("corel").
spam_word("direct").
spam_word("medical").
spam_word("corp").
spam_word("website").
spam_word("both").
spam_word("department").
spam_word("title").
spam_word("approved").
spam_word("macromedia").
spam_word("secure").
spam_word("words").
spam_word("dealer").
spam_word("production").
spam_word("usa").
spam_word("hello").
spam_word("valium").
spam_word("knle").
spam_word("exchange").
spam_word("term").
spam_word("offering").
spam_word("remember").
spam_word("months").
spam_word("did").
spam_word("features").
spam_word("potential").
spam_word("effective").
spam_word("id").
spam_word("deals").
spam_word("january").
spam_word("hard").
spam_word("few").
spam_word("500").
spam_word("still").
spam_word("intel").
spam_word("22").
spam_word("tel").
spam_word("charge").
spam_word("small").
spam_word("safe").
spam_word("iit").
spam_word("demokritos").
spam_word("wide").
spam_word("rolex").
spam_word("fund").
spam_word("edition").
spam_word("calls").
spam_word("quick").
spam_word("factors").
spam_word("al").
spam_word("type").
spam_word("18").
spam_word("request").
spam_word("form").
spam_word("data").
spam_word("solution").
spam_word("shall").
spam_word("marketing").
spam_word("transaction").
spam_word("format").
spam_word("fast").
spam_word("medications").
spam_word("network").
spam_word("say").
spam_word("end").
spam_word("commercial").
spam_word("exactly").
spam_word("doctor").
spam_word("music").
spam_word("express").
spam_word("projects").
spam_word("might").
spam_word("nothing").
spam_word("financing").
spam_word("23").
spam_word("ibm").
spam_word("open").
spam_word("speculative").
spam_word("1933").
spam_word("latest").
spam_word("profile").
spam_word("zone").
spam_word("reason").
spam_word("important").
spam_word("letter").
spam_word("start").
spam_word("women").
spam_word("getting").
spam_word("gold").
spam_word("guarantee").
spam_word("rnd").
spam_word("agreement").
spam_word("pc").
spam_word("control").
spam_word("actual").
spam_word("personal").
spam_word("availability").
spam_word("error").
spam_word("box").
spam_word("dear").
spam_word("rx").
spam_word("huge").
spam_word("55").
spam_word("corporation").
spam_word("expect").
spam_word("trading").
spam_word("purchase").
spam_word("jebel").
spam_word("plain").
spam_word("once").
spam_word("300").
spam_word("national").
spam_word("perfect").
spam_word("late").
spam_word("digital").
spam_word("creative").
spam_word("lots").
spam_word("ex").
spam_word("instant").
spam_word("penis").
spam_word("relief").
spam_word("currently").
spam_word("really").
spam_word("cf").
spam_word("north").
spam_word("numbers").
spam_word("plans").
spam_word("believes").
spam_word("usb").
spam_word("south").
spam_word("thing").
spam_word("recent").
spam_word("note").
spam_word("systems").
spam_word("able").
spam_word("contains").
spam_word("possible").
spam_word("known").
spam_word("dvd").
spam_word("side").
spam_word("complete").
spam_word("prize").
spam_word("alt").
spam_word("card").
spam_word("inherent").
spam_word("draw").
spam_word("necessary").
spam_word("government").
spam_word("become").
spam_word("ooking").
spam_word("oi").
spam_word("four").
spam_word("75").
spam_word("passed").
spam_word("105").
spam_word("continue").
spam_word("seek").
spam_word("none").
spam_word("original").
spam_word("investor").
spam_word("instructions").
spam_word("bill").
spam_word("plus").
spam_word("choose").
spam_word("200").
spam_word("write").
spam_word("case").
spam_word("girls").
spam_word("darial").
spam_word("found").
spam_word("application").
spam_word("popular").
spam_word("respect").
spam_word("assumptions").
spam_word("identified").
spam_word("version").
spam_word("times").
spam_word("wi").
spam_word("yahoo").
spam_word("half").
spam_word("wireless").
spam_word("canon").
spam_word("intended").
spam_word("gra").
spam_word("unique").
spam_word("think").
spam_word("yap").
spam_word("selected").
spam_word("35").
spam_word("him").
spam_word("claim").
spam_word("09").
spam_word("learn").
spam_word("0310041").
spam_word("delivery").
spam_word("expected").
spam_word("1934").
spam_word("anticipated").
spam_word("aware").
spam_word("conflict").
spam_word("experience").
spam_word("operating").
spam_word("sec").
spam_word("director").
spam_word("weeks").
spam_word("already").
spam_word("export").
spam_word("101").
spam_word("shown").
spam_word("dr").
spam_word("state").
spam_word("away").
spam_word("door").
spam_word("interested").
spam_word("everything").
spam_word("longer").
spam_word("happy").
spam_word("voice").
spam_word("video").
spam_word("history").
spam_word("play").
spam_word("dell").
spam_word("iii").
spam_word("48").
spam_word("meet").
spam_word("exclusive").
spam_word("cds").
spam_word("expects").
spam_word("given").
spam_word("immediately").
spam_word("sony").
spam_word("add").
spam_word("co").
spam_word("big").
spam_word("age").
spam_word("sexual").
spam_word("discount").
spam_word("pill").
spam_word("0424040").
spam_word("ftar").
spam_word("alert").
spam_word("media").
spam_word("13").
spam_word("clearance").
spam_word("toshiba").
spam_word("logos").
spam_word("respective").
spam_word("z").
spam_word("share").
spam_word("young").
spam_word("fat").
spam_word("needs").
spam_word("la").
spam_word("team").
spam_word("occur").
spam_word("advisor").
spam_word("effort").
spam_word("thought").
spam_word("somehow").
spam_word("trademarks").
spam_word("ca").
spam_word("problem").
spam_word("revenue").
spam_word("q").
spam_word("en").
spam_word("simply").
spam_word("payment").
spam_word("received").
spam_word("htm").
spam_word("partner").
spam_word("head").
spam_word("materially").
spam_word("representative").
spam_word("solicitation").
spam_word("includes").
spam_word("upon").
spam_word("soon").
spam_word("gb").
spam_word("listing").
spam_word("viewsonic").
spam_word("resellers").
spam_word("paragraph").
spam_word("congress").
spam_word("2002").
spam_word("titles").
spam_word("capital").
spam_word("shipped").
spam_word("soma").
spam_word("claims").
spam_word("local").
spam_word("vicodin").
spam_word("options").
spam_word("fontfont").
spam_word("global").
spam_word("around").
spam_word("ability").
spam_word("revenues").
spam_word("robotics").
spam_word("gotten").
spam_word("1618").
spam_word("code").
spam_word("page").
spam_word("enterprise").
spam_word("value").
spam_word("another").
spam_word("acquisition").
spam_word("won").
spam_word("cellpadding").
spam_word("symbol").
spam_word("presently").
spam_word("herein").
spam_word("near").
spam_word("user").
spam_word("materia").
spam_word("increased").
spam_word("officer").
spam_word("complaints").
spam_word("until").
spam_word("quarter").
spam_word("highly").
spam_word("compaq").
spam_word("hewlett").
spam_word("8834464").
spam_word("8834454").
spam_word("legislation").
spam_word("4176").
spam_word("point").
spam_word("short").
spam_word("care").
spam_word("lowest").
spam_word("research").
spam_word("old").
spam_word("live").
spam_word("normally").
spam_word("story").
spam_word("category").
spam_word("1226030").
spam_word("attention").
spam_word("solutions").
spam_word("announced").
spam_word("says").
spam_word("create").
spam_word("29").
spam_word("facts").
spam_word("confirm").
spam_word("worth").
spam_word("following").
spam_word("exploration").
spam_word("flash").
spam_word("enquiries").
spam_word("dealers").
spam_word("packard").
spam_word("iomega").
spam_word("aopen").
spam_word("apc").
spam_word("cisco").
spam_word("intellinet").
spam_word("targus").
spam_word("suggestions").
spam_word("customerservice").
spam_word("someone").
spam_word("foreign").
spam_word("nomad").
spam_word("owners").
spam_word("opportunity").
spam_word("rm").
spam_word("overnight").
spam_word("operations").
spam_word("construed").
spam_word("fill").
spam_word("uae").
spam_word("guaranteed").
spam_word("minutes").
spam_word("thousands").
spam_word("wife").
spam_word("president").
spam_word("matter").
spam_word("manager").
spam_word("se").
spam_word("ship").
spam_word("31").
spam_word("drug").
spam_word("28").
spam_word("agent").
spam_word("predictions").
spam_word("objectives").
spam_word("pertaining").
spam_word("understood").
spam_word("represent").
spam_word("sure").
spam_word("licensed").
spam_word("52").
spam_word("billion").
spam_word("lottery").
spam_word("acceptance").
spam_word("reference").
spam_word("related").
spam_word("04").
spam_word("put").
spam_word("ready").
spam_word("ordering").
spam_word("deal").
spam_word("store").
spam_word("car").
spam_word("98").
spam_word("normal").
spam_word("everyone").
spam_word("itoy").
spam_word("bad").
spam_word("advanced").
spam_word("leader").
spam_word("american").
spam_word("anticipates").
spam_word("indicating").
spam_word("deciding").
spam_word("mind").
spam_word("positive").
spam_word("opinion").
spam_word("immediate").
spam_word("five").
spam_word("56").
spam_word("zonedubai").
spam_word("emirates").
spam_word("aeor").
spam_word("key").
spam_word("advantage").
spam_word("sum").
spam_word("general").
spam_word("air").
spam_word("filings").
spam_word("savings").
spam_word("friend").
spam_word("hope").
spam_word("hey").
spam_word("03").
spam_word("weekend").
spam_word("begin").
spam_word("waste").

% Top ham words
ham_word("the").
ham_word("to").
ham_word("ect").
ham_word("for").
ham_word("and").
ham_word("hou").
ham_word("enron").
ham_word("subject").
ham_word("on").
ham_word("a").
ham_word("of").
ham_word("you").
ham_word("i").
ham_word("is").
ham_word("this").
ham_word("in").
ham_word("2000").
ham_word("be").
ham_word("will").
ham_word("that").
ham_word("from").
ham_word("have").
ham_word("we").
ham_word("at").
ham_word("gas").
ham_word("deal").
ham_word("com").
ham_word("please").
ham_word("if").
ham_word("with").
ham_word("meter").
ham_word("am").
ham_word("cc").
ham_word("by").
ham_word("pm").
ham_word("hpl").
ham_word("it").
ham_word("are").
ham_word("s").
ham_word("your").
ham_word("me").
ham_word("2001").
ham_word("1").
ham_word("as").
ham_word("not").
ham_word("daren").
ham_word("000").
ham_word("00").
ham_word("10").
ham_word("thanks").
ham_word("_").
ham_word("or").
ham_word("re").
ham_word("01").
ham_word("corp").
ham_word("3").
ham_word("d").
ham_word("2").
ham_word("any").
ham_word("know").
ham_word("can").
ham_word("mmbtu").
ham_word("e").
ham_word("was").
ham_word("11").
ham_word("j").
ham_word("forwarded").
ham_word("need").
ham_word("12").
ham_word("03").
ham_word("has").
ham_word("farmer").
ham_word("should").
ham_word("let").
ham_word("4").
ham_word("attached").
ham_word("5").
ham_word("our").
ham_word("all").
ham_word("xls").
ham_word("see").
ham_word("02").
ham_word("new").
ham_word("up").
ham_word("there").
ham_word("may").
ham_word("do").
ham_word("l").
ham_word("an").
ham_word("04").
ham_word("t").
ham_word("0").
ham_word("contract").
ham_word("volume").
ham_word("would").
ham_word("robert").
ham_word("day").
ham_word("sitara").
ham_word("these").
ham_word("been").
ham_word("05").
ham_word("nom").
ham_word("out").
ham_word("they").
ham_word("09").
ham_word("so").
ham_word("08").
ham_word("texas").
ham_word("get").
ham_word("volumes").
ham_word("month").
ham_word("but").
ham_word("30").
ham_word("into").
ham_word("questions").
ham_word("what").
ham_word("pec").
ham_word("m").
ham_word("99").
ham_word("deals").
ham_word("6").
ham_word("price").
ham_word("ena").
ham_word("bob").
ham_word("th").
ham_word("20").
ham_word("flow").
ham_word("message").
ham_word("9").
ham_word("energy").
ham_word("file").
ham_word("change").
ham_word("mail").
ham_word("production").
ham_word("sent").
ham_word("7").
ham_word("06").
ham_word("information").
ham_word("time").
ham_word("no").
ham_word("call").
ham_word("following").
ham_word("07").
ham_word("my").
ham_word("31").
ham_word("nomination").
ham_word("8").
ham_word("gary").
ham_word("ticket").
ham_word("713").
ham_word("daily").
ham_word("15").
ham_word("also").
ham_word("which").
ham_word("mary").
ham_word("us").
ham_word("some").
ham_word("about").
ham_word("when").
ham_word("one").
ham_word("21").
ham_word("their").
ham_word("march").
ham_word("april").
ham_word("july").
ham_word("original").
ham_word("16").
ham_word("just").
ham_word("25").
ham_word("x").
ham_word("plant").
ham_word("company").
ham_word("melissa").
ham_word("28").
ham_word("p").
ham_word("per").
ham_word("houston").
ham_word("24").
ham_word("effective").
ham_word("teco").
ham_word("only").
ham_word("back").
ham_word("vance").
ham_word("below").
ham_word("net").
ham_word("them").
ham_word("tenaska").
ham_word("14").
ham_word("were").
ham_word("he").
ham_word("like").
ham_word("22").
ham_word("days").
ham_word("now").
ham_word("sale").
ham_word("23").
ham_word("list").
ham_word("fw").
ham_word("george").
ham_word("june").
ham_word("changes").
ham_word("26").
ham_word("18").
ham_word("ami").
ham_word("pat").
ham_word("purchase").
ham_word("13").
ham_word("could").
ham_word("julie").
ham_word("smith").
ham_word("help").
ham_word("set").
ham_word("29").
ham_word("transport").
ham_word("want").
ham_word("27").
ham_word("19").
ham_word("other").
ham_word("17").
ham_word("jackie").
ham_word("agreement").
ham_word("make").
ham_word("well").
ham_word("b").
ham_word("system").
ham_word("don").
ham_word("number").
ham_word("first").
ham_word("who").
ham_word("north").
ham_word("contact").
ham_word("email").
ham_word("here").
ham_word("aimee").
ham_word("january").
ham_word("sales").
ham_word("noms").
ham_word("had").
ham_word("c").
ham_word("lisa").
ham_word("tap").
ham_word("through").
ham_word("more").
ham_word("desk").
ham_word("america").
ham_word("susan").
ham_word("david").
ham_word("pipeline").
ham_word("october").
ham_word("actuals").
ham_word("hsc").
ham_word("michael").
ham_word("mark").
ham_word("each").
ham_word("w").
ham_word("report").
ham_word("order").
ham_word("needs").
ham_word("cotten").
ham_word("over").
ham_word("think").
ham_word("how").
ham_word("august").
ham_word("she").
ham_word("management").
ham_word("taylor").
ham_word("today").
ham_word("megan").
ham_word("week").
ham_word("iv").
ham_word("steve").
ham_word("chokshi").
ham_word("friday").
ham_word("thank").
ham_word("request").
ham_word("under").
ham_word("delivery").
ham_word("john").
ham_word("take").
ham_word("fyi").
ham_word("next").
ham_word("forward").
ham_word("tom").
ham_word("duke").
ham_word("hplc").
ham_word("point").
ham_word("oil").
ham_word("co").
ham_word("date").
ham_word("less").
ham_word("work").
ham_word("business").
ham_word("last").
ham_word("september").
ham_word("did").
ham_word("tu").
ham_word("name").
ham_word("group").
ham_word("being").
ham_word("o").
ham_word("november").
ham_word("after").
ham_word("wellhead").
ham_word("december").
ham_word("clynes").
ham_word("k").
ham_word("february").
ham_word("use").
ham_word("eastrans").
ham_word("total").
ham_word("feb").
ham_word("activity").
ham_word("100").
ham_word("spot").
ham_word("lloyd").
ham_word("issue").
ham_word("tickets").
ham_word("counterparty").
ham_word("sure").
ham_word("meeting").
ham_word("graves").
ham_word("two").
ham_word("service").
ham_word("go").
ham_word("line").
ham_word("unify").
ham_word("currently").
ham_word("fuel").
ham_word("brian").
ham_word("team").
ham_word("monday").
ham_word("ll").
ham_word("due").
ham_word("meters").
ham_word("aol").
ham_word("http").
ham_word("resources").
ham_word("revised").
ham_word("inc").
ham_word("na").
ham_word("then").
ham_word("until").
ham_word("services").
ham_word("send").
ham_word("same").
ham_word("f").
ham_word("40").
ham_word("lee").
ham_word("actual").
ham_word("still").
ham_word("98").
ham_word("down").
ham_word("utilities").
ham_word("pg").
ham_word("year").
ham_word("supply").
ham_word("global").
ham_word("look").
ham_word("contracts").
ham_word("off").
ham_word("above").
ham_word("h").
ham_word("fax").
ham_word("txu").
ham_word("based").
ham_word("jan").
ham_word("50").
ham_word("meyers").
ham_word("tx").
ham_word("both").
ham_word("howard").
ham_word("hplno").
ham_word("rate").
ham_word("thursday").
ham_word("fee").
ham_word("rita").
ham_word("process").
ham_word("lannou").
ham_word("give").
ham_word("received").
ham_word("again").
ham_word("end").
ham_word("created").
ham_word("office").
ham_word("nominations").
ham_word("hanks").
ham_word("since").
ham_word("between").
ham_word("james").
ham_word("young").
ham_word("going").
ham_word("note").
ham_word("allocation").
ham_word("phone").
ham_word("does").
ham_word("where").
ham_word("made").
ham_word("demand").
ham_word("trading").
ham_word("entered").
ham_word("r").
ham_word("500").
ham_word("done").
ham_word("find").
ham_word("than").
ham_word("before").
ham_word("available").
ham_word("free").
ham_word("correct").
ham_word("those").
ham_word("thru").
ham_word("check").
ham_word("tuesday").
ham_word("pefs").
ham_word("data").
ham_word("enronxgate").
ham_word("mike").
ham_word("put").
ham_word("however").
ham_word("weissman").
ham_word("deliveries").
ham_word("manager").
ham_word("doc").
ham_word("gcs").
ham_word("cec").
ham_word("katherine").
ham_word("once").
ham_word("dec").
ham_word("able").
ham_word("wynne").
ham_word("additional").
ham_word("issues").
ham_word("show").
ham_word("45").
ham_word("camp").
ham_word("carlos").
ham_word("allocated").
ham_word("hplo").
ham_word("invoice").
ham_word("allen").
ham_word("term").
ham_word("scheduled").
ham_word("iferc").
ham_word("during").
ham_word("path").
ham_word("because").
ham_word("gathering").
ham_word("his").
ham_word("keep").
ham_word("regarding").
ham_word("her").
ham_word("fuels").
ham_word("natural").
ham_word("its").
ham_word("place").
ham_word("numbers").
ham_word("continue").
ham_word("receive").
ham_word("logistics").
ham_word("product").
ham_word("people").
ham_word("provide").
ham_word("spreadsheet").
ham_word("click").
ham_word("ls").
ham_word("anita").
ham_word("pricing").
ham_word("id").
ham_word("transaction").
ham_word("jones").
ham_word("buyback").
ham_word("high").
ham_word("period").
ham_word("equistar").
ham_word("marketing").
ham_word("access").
ham_word("create").
ham_word("fred").
ham_word("good").
ham_word("said").
ham_word("sherlyn").
ham_word("anything").
ham_word("www").
ham_word("field").
ham_word("problem").
ham_word("wednesday").
ham_word("support").
ham_word("1999").
ham_word("flowed").
ham_word("scheduling").
ham_word("someone").
ham_word("pops").
ham_word("address").
ham_word("customer").
ham_word("katy").
ham_word("pay").
ham_word("entex").
ham_word("possible").
ham_word("review").
ham_word("home").
ham_word("update").
ham_word("ees").
ham_word("plan").
ham_word("zero").
ham_word("operations").
ham_word("control").
ham_word("prior").
ham_word("firm").
ham_word("clem").
ham_word("further").
ham_word("st").
ham_word("tess").
ham_word("either").
ham_word("darren").
ham_word("soon").
ham_word("swing").
ham_word("coastal").
ham_word("current").
ham_word("months").
ham_word("way").
ham_word("calpine").
ham_word("scott").
ham_word("brenda").
ham_word("hours").
ham_word("valley").
ham_word("needed").
ham_word("must").
ham_word("accounting").
ham_word("employees").
ham_word("very").
ham_word("ve").
ham_word("changed").
ham_word("gco").
ham_word("start").
ham_word("aep").
ham_word("midcon").
ham_word("survey").
ham_word("stephanie").
ham_word("right").
ham_word("another").
ham_word("ray").
ham_word("tomorrow").
ham_word("im").
ham_word("ranch").
ham_word("donna").
ham_word("imbalance").
ham_word("working").
ham_word("agree").
ham_word("stacey").
ham_word("cotton").
ham_word("karen").
ham_word("ces").
ham_word("donald").
ham_word("acton").
ham_word("add").
ham_word("power").
ham_word("800").
ham_word("rodriguez").
ham_word("parker").
ham_word("thu").
ham_word("used").
ham_word("lauri").
ham_word("follows").
ham_word("35").
ham_word("sept").
ham_word("beaumont").
ham_word("richard").
ham_word("valid").
ham_word("vlt").
ham_word("cornhusker").
ham_word("advise").
ham_word("old").
ham_word("jim").
ham_word("market").
ham_word("hotmail").
ham_word("schedule").
ham_word("redeliveries").
ham_word("development").
ham_word("cynthia").
ham_word("rates").
ham_word("victor").
ham_word("corporation").
ham_word("storage").
ham_word("morning").
ham_word("much").
ham_word("great").
ham_word("pipe").
ham_word("carthage").
ham_word("feedback").
ham_word("customers").
ham_word("schumack").
ham_word("copy").
ham_word("charlie").
ham_word("paid").
ham_word("using").
ham_word("dave").
ham_word("increase").
ham_word("why").
ham_word("n").
ham_word("beginning").
ham_word("web").
ham_word("stone").
ham_word("reinhardt").
ham_word("risk").
ham_word("requested").
ham_word("luong").
ham_word("shut").
ham_word("come").
ham_word("ken").
ham_word("him").
ham_word("mobil").
ham_word("getting").
ham_word("part").
ham_word("every").
ham_word("called").
ham_word("account").
ham_word("believe").
ham_word("book").
ham_word("lsk").
ham_word("cheryl").
ham_word("wanted").
ham_word("lst").
ham_word("hplnl").
ham_word("ic").
ham_word("confirmed").
ham_word("herod").
ham_word("methanol").
ham_word("producer").
ham_word("jeff").
ham_word("handle").
ham_word("extend").
ham_word("trade").
ham_word("products").
ham_word("amount").
ham_word("page").
ham_word("thomas").
ham_word("32").
ham_word("34").
ham_word("281").
ham_word("albrecht").
ham_word("6353").
ham_word("while").
ham_word("revision").
ham_word("buy").
ham_word("person").
ham_word("papayoti").
ham_word("form").
ham_word("already").
ham_word("type").
ham_word("operating").
ham_word("within").
ham_word("center").
ham_word("shows").
ham_word("something").
ham_word("financial").
ham_word("bryan").
ham_word("cover").
ham_word("dfarmer").
ham_word("extended").
ham_word("lamphier").
ham_word("yet").
ham_word("best").
ham_word("three").
ham_word("exxon").
ham_word("union").
ham_word("east").
ham_word("44").
ham_word("valero").
ham_word("internet").
ham_word("hope").
ham_word("error").
ham_word("edward").
ham_word("problems").
ham_word("looking").
ham_word("cleburne").
ham_word("baumbach").
ham_word("clear").
ham_word("everyone").
ham_word("project").
ham_word("location").
ham_word("poorman").
ham_word("nominated").
ham_word("confirm").
ham_word("via").
ham_word("basis").
ham_word("anyone").
ham_word("updated").
ham_word("position").
ham_word("addition").
ham_word("listed").
ham_word("around").
ham_word("33").
ham_word("liz").
ham_word("g").
ham_word("jennifer").
ham_word("tax").
ham_word("47").
ham_word("sorry").
ham_word("central").
ham_word("devon").
ham_word("dow").
ham_word("might").
ham_word("question").
ham_word("42").
ham_word("afternoon").
ham_word("el").
ham_word("dy").
ham_word("feel").
ham_word("janet").
ham_word("else").
ham_word("eol").
ham_word("48").
ham_word("status").
ham_word("koch").
ham_word("several").
ham_word("lsp").
ham_word("hesse").
ham_word("39").
ham_word("neal").
ham_word("58").
ham_word("info").
ham_word("got").
ham_word("waha").
ham_word("oasis").
ham_word("cut").
ham_word("left").
ham_word("future").
ham_word("38").
ham_word("yahoo").
ham_word("most").
ham_word("weekend").
ham_word("added").
ham_word("830").
ham_word("sell").
ham_word("stack").
ham_word("36").
ham_word("state").
ham_word("coming").
ham_word("training").
ham_word("purchases").
ham_word("riley").
ham_word("53").
ham_word("probably").
ham_word("estimate").
ham_word("move").
ham_word("exception").
ham_word("enserch").
ham_word("such").
ham_word("56").
ham_word("unit").
ham_word("star").
ham_word("enrononline").
ham_word("lp").
ham_word("long").
ham_word("stella").
ham_word("special").
ham_word("many").
ham_word("items").
ham_word("different").
ham_word("mid").
ham_word("employee").
ham_word("outage").
ham_word("big").
ham_word("098").
ham_word("mcf").
ham_word("monthly").
ham_word("link").
ham_word("follow").
ham_word("cernosek").
ham_word("mailto").
ham_word("pathed").
ham_word("complete").
ham_word("55").
ham_word("portfolio").
ham_word("853").
ham_word("hall").
ham_word("aepin").
ham_word("together").
ham_word("program").
ham_word("direct").
ham_word("kevin").
ham_word("priced").
ham_word("60").
ham_word("few").
ham_word("52").
ham_word("reports").
ham_word("discuss").
ham_word("apache").
ham_word("online").
ham_word("enter").
ham_word("things").
ham_word("tejas").
ham_word("industrial").
ham_word("physical").
ham_word("close").
ham_word("saturday").
ham_word("return").
ham_word("bellamy").
ham_word("even").
ham_word("having").
ham_word("option").
ham_word("withers").
ham_word("payment").
ham_word("final").
ham_word("reflect").
ham_word("without").
ham_word("85").
ham_word("morris").
ham_word("mm").
ham_word("notice").
ham_word("receipt").
ham_word("lone").
ham_word("necessary").
ham_word("49").
ham_word("spoke").
ham_word("read").
ham_word("offer").
ham_word("boas").
ham_word("thought").
ham_word("party").
ham_word("approval").
ham_word("williams").
ham_word("therefore").
ham_word("points").
ham_word("hi").
ham_word("password").
ham_word("visit").
ham_word("37").
ham_word("200").
ham_word("doing").
ham_word("include").
ham_word("london").
ham_word("transportation").
ham_word("suite").
ham_word("54").
ham_word("avila").
ham_word("verify").
ham_word("case").
ham_word("facility").
ham_word("mccoy").
ham_word("approximately").
ham_word("exchange").
ham_word("easttexas").
ham_word("performance").
ham_word("superty").
ham_word("settlements").
ham_word("elizabeth").
ham_word("hesco").
ham_word("57").
ham_word("zone").
ham_word("trying").
ham_word("william").
ham_word("bruce").
ham_word("nov").
ham_word("lamadrid").
ham_word("president").
ham_word("cdnow").
ham_word("46").
ham_word("hakemack").
ham_word("gpgfin").
ham_word("showing").
ham_word("charlotte").
ham_word("run").
ham_word("track").
ham_word("vacation").
ham_word("herrera").
ham_word("nguyen").
ham_word("site").
ham_word("meet").
ham_word("intended").
ham_word("cannot").
ham_word("additionally").
ham_word("legal").
ham_word("better").
ham_word("beverly").
ham_word("sandi").
ham_word("included").
ham_word("details").
ham_word("oct").
ham_word("walker").
ham_word("700").
ham_word("51").
ham_word("paso").
ham_word("little").
ham_word("cost").
ham_word("asked").
ham_word("ltd").
ham_word("cp").
ham_word("ask").
ham_word("base").
ham_word("41").
ham_word("sally").
ham_word("index").
ham_word("activities").
ham_word("eileen").
ham_word("try").
ham_word("told").
ham_word("talk").
ham_word("kcs").
ham_word("hill").
ham_word("city").
ham_word("impact").
ham_word("tina").
ham_word("section").
ham_word("including").
ham_word("staff").
ham_word("moved").
ham_word("letter").
ham_word("earl").
ham_word("purchased").
ham_word("reliantenergy").
ham_word("requirements").
ham_word("4179").
ham_word("sat").
ham_word("king").
ham_word("exploration").
ham_word("bridge").
ham_word("night").
ham_word("costs").
ham_word("expedia").
ham_word("johnson").
ham_word("eric").
ham_word("comments").
ham_word("completed").
ham_word("345").
ham_word("9497").
ham_word("ponton").
ham_word("gomes").
ham_word("flowing").
ham_word("rebecca").
ham_word("love").
ham_word("kimberly").
ham_word("capacity").
ham_word("hub").
ham_word("enw").
ham_word("understanding").
ham_word("print").
ham_word("channel").
ham_word("delivered").
ham_word("too").
ham_word("ensure").
ham_word("stock").
ham_word("59").
ham_word("dan").
ham_word("1266").
ham_word("enerfin").
ham_word("neon").
ham_word("215").
ham_word("found").
ham_word("expense").
ham_word("response").
ham_word("didn").
ham_word("missing").
ham_word("rd").
ham_word("looks").
ham_word("terry").
ham_word("btu").
ham_word("tisdale").
ham_word("300").
ham_word("website").
ham_word("tell").
ham_word("informed").
ham_word("version").
ham_word("later").
ham_word("dynegy").
ham_word("strangers").
ham_word("tammy").
ham_word("allow").
ham_word("related").
ham_word("prices").
ham_word("whole").
ham_word("area").
ham_word("tetco").
ham_word("gulf").
ham_word("etc").
ham_word("mckay").
ham_word("directly").
ham_word("bill").
ham_word("orders").
ham_word("select").
ham_word("invoices").
ham_word("allocate").
ham_word("distribution").
ham_word("rc").
ham_word("understand").
ham_word("image").
ham_word("answer").
ham_word("box").
ham_word("content").
ham_word("neuweiler").
ham_word("transactions").
ham_word("early").
ham_word("012").
ham_word("loss").
ham_word("document").
ham_word("sunday").
ham_word("canada").
ham_word("unsubscribe").
ham_word("jill").
ham_word("guys").

% Kiểm tra email có phải spam hay ham
classify_email(Text, Result, SpamPercent, HamPercent) :-
    split_string(Text, " ", "", Words),
    findall(W, (member(W, Words), spam_word(W)), SpamWords),
    findall(W, (member(W, Words), ham_word(W)), HamWords),
    length(SpamWords, SpamCount),
    length(HamWords, HamCount),
    Total is SpamCount + HamCount,
    (Total > 0 ->
            SpamPercent is (SpamCount / Total) * 100,
            HamPercent is (HamCount / Total) * 100;
            SpamPercent = 0.0,
            HamPercent = 0.0
    ),
    (SpamCount > HamCount -> Result = "spam"; Result = "ham").